nx.json, package-lock.json, package.json
Also created issue to connect it later: #35
=> Remove Nx Cloud (unclaimed workspace)

package-lock.json, packages/utils/src/index.ts, packages/utils/src/lib/collect/implementation/execute-process.spec.ts, packages/utils/src/lib/collect/implementation/execute-process.ts
- the logic
- tests
- JS docs
- exports as public API
closes #43
=> feat(utils): add command line args helper

packages/utils/src/lib/collect/implementation/execute-process.ts, packages/utils/src/lib/collect/implementation/utils.spec.ts, packages/utils/src/lib/collect/implementation/utils.ts, packages/utils/src/lib/collect/index.ts
- duration formatting helper and tests
- usage of the duration formatter in the collect logic
closes #56
=> refactor(utils): format duration, add tests

packages/core/src/lib/commands/upload.spec.ts
See: https://github.com/flowup/quality-metrics-portal/issues/112
=> test(core): mock uploadToPortal with correct return type

packages/models/test/fixtures/categories.mock.ts, packages/models/test/fixtures/eslint-audits.mock.ts, packages/models/test/fixtures/eslint-plugin.mock.ts, packages/models/test/fixtures/lighthouse-plugin.mock.ts, packages/models/test/fixtures/report.mock.ts
We can use this for playing around with report formatting for Markdown and stdout.
<details>
<summary>report.json</summary>
<pre><code>{
"packageName": "@code-pushup/core",
"version": "0.1.0",
"date": "2023-10-18T07:49:45.506Z",
"duration": 1652,
"categories": [
{
"slug": "performance",
"title": "Performance",
"refs": [
{
"type": "group",
"plugin": "lighthouse",
"slug": "performance",
"weight": 1
},
{
"type": "audit",
"plugin": "eslint",
"slug": "react-jsx-key",
"weight": 0
}
]
},
{
"slug": "bug-prevention",
"title": "Bug prevention",
"refs": [
{
"type": "audit",
"plugin": "eslint",
"slug": "no-cond-assign",
"weight": 1
},
{
"type": "audit",
"plugin": "eslint",
"slug": "no-const-assign",
"weight": 1
},
{
"type": "audit",
"plugin": "eslint",
"slug": "no-debugger",
"weight": 1
},
{
"type": …
=> test(models): prepare test fixtures with more realistic report data

packages/cli/src/lib/yargs-cli.ts
=> fix(cli): changed persist format options to array

e2e/cli-e2e/tests/__snapshots__/help.spec.ts.snap, packages/cli/src/lib/yargs-cli.ts
Disabled --version option
Closes #124
=> feat(cli): disabled version option

packages/cli/src/lib/yargs-cli.spec.ts, packages/cli/src/lib/yargs-cli.ts
=> fix(cli): parse multiple config args to last item of array

README.md, packages/cli/README.md, packages/core/README.md, packages/models/README.md, packages/plugin-eslint/README.md, packages/utils/README.md
[link to updated README](https://github.com/flowup/quality-metrics-cli/tree/improve-readmes#readme)
=> docs: improve READMEs with emojis and nicer formatting

.github/workflows/ci.yml, README.md, nx.json
=> ci: adds `maxWarnings=0` as default for the lint target

commitlint.config.js, package-lock.json, package.json
=> chore: add imperative rule to commitlint

e2e/cli-e2e/tests/__snapshots__/collect.spec.ts.snap, packages/plugin-eslint/README.md, packages/plugin-eslint/src/lib/__snapshots__/eslint-plugin.spec.ts.snap, packages/plugin-eslint/src/lib/eslint-plugin.ts, packages/plugin-eslint/src/lib/meta/groups.spec.ts, packages/plugin-eslint/src/lib/meta/groups.ts, packages/plugin-eslint/src/lib/meta/index.ts, packages/plugin-eslint/src/lib/meta/rules.spec.ts, packages/plugin-eslint/src/lib/meta/rules.ts, packages/plugin-eslint/src/lib/runner.spec.ts, packages/utils/src/index.ts, packages/utils/src/lib/utils.ts
=> feat(plugin-eslint): create groups from rules' metadata

.eslintrc.json, packages/cli/src/lib/collect/command-object.spec.ts, packages/cli/src/lib/print-config/command-object.spec.ts, packages/core/src/lib/collect-and-persist.spec.ts, packages/core/src/lib/implementation/execute-plugin.spec.ts, packages/core/src/lib/implementation/persist.spec.ts, packages/core/src/lib/upload.spec.ts, packages/nx-plugin/src/generators/init/generator.spec.ts, packages/plugin-eslint/src/lib/__snapshots__/eslint-plugin.spec.ts.snap, packages/plugin-eslint/src/lib/eslint-plugin.spec.ts, packages/utils/src/lib/execute-process.spec.ts, packages/utils/src/lib/progress.spec.ts, packages/utils/src/lib/report-to-stdout.spec.ts, packages/utils/src/lib/scoring.spec.ts, packages/utils/src/lib/verbose-utils.spec.ts
Closes #204 
Updated Code PushUp scores
=> test: fix and apply vitest ESLint rules

packages/cli/src/lib/yargs-cli.spec.ts, packages/cli/src/lib/yargs-cli.ts
=> refactor: remove demandCommand option to reduce API surface

packages/utils/src/lib/report.spec.ts, packages/utils/src/lib/report.ts
=> refactor(utils): remove unused code

.github/workflows/ci.yml
=> ci: add macos-latest to test matrix

packages/cli/src/lib/implementation/model.ts, packages/utils/src/lib/execute-process.spec.ts, packages/utils/src/lib/execute-process.ts
=> fix(utils,cli): remove all mentions of the `interactive` option

e2e/cli-e2e/mocks/code-pushup.config.js, e2e/cli-e2e/mocks/code-pushup.config.mjs, e2e/cli-e2e/mocks/code-pushup.config.ts, e2e/cli-e2e/tests/print-config.spec.ts
=> refactor(cli-e2e): use eslint plugin in e2e tests

README.md
=> chore(tools): add badges to README

e2e/cli-e2e/tests/__snapshots__/help.e2e.test.ts.snap, packages/cli/README.md, packages/cli/src/lib/implementation/core-config-options.ts, packages/core/src/lib/implementation/persist.integration.test.ts, packages/core/src/lib/implementation/persist.ts, packages/models/src/lib/persist-config.ts, packages/nx-plugin/src/generators/configuration/files/code-pushup.config.ts.template
=> refactor(cli): remove 'stdout' option from report output formats

packages/cli/README.md
=> docs(cli): update CLI documentation in README

.github/workflows/release.yml
=> ci: collect and upload code pushup report after release

packages/plugin-eslint/src/lib/runner/transform.ts
=> chore(plugin-eslint): change eslint displayValue from 0 to passed

e2e/cli-e2e/tests/__snapshots__/collect.e2e.test.ts.snap, packages/models/test/fixtures/eslint-audits.mock.ts, packages/plugin-eslint/src/lib/__snapshots__/runner.integration.test.ts.snap, packages/plugin-eslint/src/lib/runner/index.ts, packages/plugin-eslint/src/lib/runner/transform.ts, packages/utils/src/lib/__snapshots__/report-to-md.integration.test.ts.snap, packages/utils/src/lib/__snapshots__/report-to-stdout.integration.test.ts.snap
Closes #305 
Implementation in PR #379 didn't have any effect.
=> feat(plugin-eslint): set "passed" displayValue for ESLint audits

.github/ISSUE_TEMPLATE/feature-request.yaml
Using the new YAML format, I created a feature request issue template.
You can check a semi-accurate preview [here](https://github.com/code-pushup/cli/blob/new-issue-template/.github/ISSUE_TEMPLATE/feature-request.yaml).
=> chore: create a feature request template

examples/plugins/src/file-size/src/file-size.plugin.integration.test.ts, examples/plugins/src/file-size/src/file-size.plugin.ts, examples/plugins/src/package-json/src/package-json.plugin.integration.test.ts, examples/plugins/src/package-json/src/package-json.plugin.ts
=> chore(examples-plugins): more distinguishable icons for custom plugins

package-lock.json, package.json, packages/core/package.json, packages/models/package.json
Motivation for update:
- more readable upload error messages (https://github.com/code-pushup/portal/pull/197)
- more icons available (https://github.com/code-pushup/portal/pull/190)
=> feat(core): improve upload error messages, extend icon set

packages/core/src/lib/implementation/execute-plugin.ts, packages/utils/src/index.ts, packages/utils/src/lib/group-by-status.ts, packages/utils/src/lib/group-by-status.unit.test.ts
Create function for grouping of settled promises by status. 
Closes #287
=> feat(core): add grouping of promise results by status

package-lock.json, package.json, packages/cli/src/lib/implementation/only-plugins-utils.unit.test.ts
See recent [@code-pushup/eslint-config releases](https://github.com/code-pushup/eslint-config/releases).
=> build: update eslint config (removes no-secrets rule)

package-lock.json, package.json, packages/core/package.json, packages/models/package.json
Fixes https://github.com/code-pushup/portal/issues/244
=> fix(core): update portal-client, fixed missing graphql dependency

e2e/cli-e2e/tests/__snapshots__/help.e2e.test.ts.snap, packages/cli/src/lib/autorun/autorun-command.ts, packages/cli/src/lib/collect/collect-command.ts, packages/cli/src/lib/commands.ts, packages/cli/src/lib/upload/upload-command.ts
=> feat(cli): add hints to commands

examples/plugins/src/package-json/src/package-json.plugin.ts, project.json
No longer needed after #361 was merged.
=> chore: remove redundant --config=code-pushup.config.ts argument

.github/labeler.yml, .github/workflows/pr-labeler.yml
Closes #329 
In this PR, I address the breaking changes of updated [labeler GitHub action](https://github.com/actions/labeler) as well as expand our current labeling logic.
=> fix(workflows): update and improve labeler options

package-lock.json, package.json, packages/cli/src/lib/autorun/autorun-command.ts, packages/cli/src/lib/implementation/logging.ts, packages/cli/src/lib/upload/upload-command.ts, packages/core/package.json, packages/core/src/lib/upload.unit.test.ts, packages/utils/src/index.ts, packages/utils/src/lib/reports/utils.ts, packages/utils/src/lib/reports/utils.unit.test.ts, testing/test-setup/src/lib/portal-client.mock.ts
=> feat(cli): print full report url after upload

e2e/cli-e2e/tests/__snapshots__/help.e2e.test.ts.snap, e2e/cli-e2e/tests/print-config.e2e.test.ts, packages/cli/README.md, packages/cli/src/lib/autorun/autorun-command.unit.test.ts, packages/cli/src/lib/collect/collect-command.unit.test.ts, packages/cli/src/lib/implementation/core-config.middleware.integration.test.ts, packages/cli/src/lib/implementation/core-config.middleware.ts, packages/cli/src/lib/implementation/core-config.middleware.unit.test.ts, packages/cli/src/lib/implementation/core-config.model.ts, packages/cli/src/lib/implementation/global.options.ts, packages/cli/src/lib/upload/upload-command.unit.test.ts, packages/core/src/lib/implementation/read-rc-file.integration.test.ts, packages/core/src/lib/implementation/read-rc-file.ts, packages/core/src/lib/types.ts, testing/test-utils/src/lib/fixtures/configs/code-pushup.needs-tsconfig.config.ts
=> feat(cli): add --tsconfig option

README.md, packages/cli/README.md, packages/core/README.md, packages/models/README.md, packages/plugin-coverage/README.md, packages/plugin-eslint/README.md, packages/plugin-lighthouse/README.md, packages/utils/README.md
- [main README](https://github.com/code-pushup/cli/blob/8946b7e81de7acca866d02fc4b2adee3056ef942/README.md)
- package READMEs:
- [cli](https://github.com/code-pushup/cli/blob/aacd19ff198af73076736d991dd28d9583a6a7fd/packages/cli/README.md)
- [core](https://github.com/code-pushup/cli/blob/aacd19ff198af73076736d991dd28d9583a6a7fd/packages/core/README.md)
- [models](https://github.com/code-pushup/cli/blob/aacd19ff198af73076736d991dd28d9583a6a7fd/packages/models/README.md)
- [utils](https://github.com/code-pushup/cli/blob/aacd19ff198af73076736d991dd28d9583a6a7fd/packages/utils/README.md)
- [eslint-plugin](https://github.com/code-pushup/cli/blob/aacd19ff198af73076736d991dd28d9583a6a7fd/packages/plugin-eslint/README.md)
- [coverage-plugin](https://github.com/code-pushup/cli/blob/aacd19ff198af730 …
=> docs: add more badges to root and package readmes

nx.json
closes #35
This commit set up Nx Cloud for your Nx workspace enabling distributed caching
and GitHub integration for fast CI and improved Developer Experience.
You can access your Nx Cloud workspace by going to 
https://cloud.nx.app/orgs/65d4d8449e4953a5ed64ff4a/workspaces/65d4d862d2adb16a45a4bc7c
=> ci: integrate Nx Cloud

packages/cli/src/lib/implementation/core-config.middleware.integration.test.ts, packages/core/src/lib/implementation/read-rc-file.integration.test.ts, testing/test-utils/.eslintrc.json, testing/test-utils/src/lib/fixtures/configs/code-pushup.needs-tsconfig.config.ts, testing/test-utils/src/lib/fixtures/configs/custom-plugin.ts, testing/test-utils/src/lib/fixtures/configs/tsconfig.json, testing/test-utils/tsconfig.lib.json
=> test(core): use custom path for testing --tsconfig

package-lock.json, package.json, packages/plugin-eslint/package.json
=> chore: resolve peer deps warning and vulnerability

code-pushup.config.ts
In order to showcase the category descriptions on portal, I added examples in our CLI configuration.
=> chore: add category descriptions

e2e/cli-e2e/tests/__snapshots__/compare.report-diff.md, packages/utils/src/lib/reports/generate-md-reports-diff.ts
=> feat(utils): include 1 decimal place when rounding score change

e2e/cli-e2e/tests/__snapshots__/compare.report-diff.md, packages/utils/src/lib/reports/__snapshots__/report-diff-added.md, packages/utils/src/lib/reports/__snapshots__/report-diff-improved.md, packages/utils/src/lib/reports/__snapshots__/report-diff-mixed.md, packages/utils/src/lib/reports/__snapshots__/report-diff-unchanged.md, packages/utils/src/lib/reports/generate-md-reports-diff.ts
=> fix(utils): consistent group emoji

packages/core/src/lib/implementation/report-to-gql.ts
[Portal link](https://staging.code-pushup.dev/portal/code-pushup/cli/commit/1860b07f0f3b4f8210e73d8d8e53880a9031e954/dashboard)
[Portal link](https://staging.code-pushup.dev/portal/code-pushup/cli/commit/c4bc4c384e683abedae1fd1383d7b45afb2a1ae1/dashboard)
=> fix(core): send isBinary flag when uploading category

.github/workflows/release.yml
Attempt to fix [broken release workflow](https://github.com/code-pushup/cli/actions/workflows/release.yml?query=branch%3Amain) based on https://github.com/code-pushup/cli/pull/591#issuecomment-2041958576.
=> ci: attempt to fix release workflow

e2e/cli-e2e/tests/__snapshots__/compare.e2e.test.ts.snap, e2e/cli-e2e/tests/__snapshots__/compare.report-diff.md, packages/core/src/lib/implementation/compare-scorables.ts, packages/models/src/lib/reports-diff.ts, packages/utils/src/lib/reports/__snapshots__/report-diff-added.md, packages/utils/src/lib/reports/__snapshots__/report-diff-improved.md, packages/utils/src/lib/reports/__snapshots__/report-diff-mixed.md, packages/utils/src/lib/reports/generate-md-reports-diff.ts, testing/test-utils/src/lib/utils/dynamic-mocks/eslint-plugin.mock.ts, testing/test-utils/src/lib/utils/dynamic-mocks/report-diff.mock.ts
=> feat(utils): format titles as links if docsUrl available in report-diff.md

packages/plugin-lighthouse/src/lib/utils.unit.test.ts
Addressing: https://github.com/code-pushup/cli/pull/593#discussion_r1559788572
=> test(plugin-lighthouse): refine tests

packages/plugin-js-packages/README.md
=> docs(plugin-js-packages): include plugin install step in README

packages/models/docs/models-reference.md, packages/models/src/lib/table.ts, packages/models/src/lib/table.unit.test.ts, packages/utils/src/lib/reports/__snapshots__/generate-md-report.unit.test.ts.snap, packages/utils/src/lib/reports/formatting.ts, packages/utils/src/lib/reports/formatting.unit.test.ts, packages/utils/src/lib/reports/generate-md-report.ts, packages/utils/src/lib/reports/generate-md-report.unit.test.ts
Motivation: possible to specify what data the table contains (e.g. _Most frequent errors_).
=> feat(models): add optional table title

nx.json
Lost my patience - convinced it does more harm than good at this point. The speed-up is negligable, and nowhere near worth the amount of mindf***s related to overzealous caching.
=> ci: disable nx cloud

packages/models/docs/models-reference.md, packages/models/src/lib/audit-output.ts, packages/models/src/lib/audit-output.unit.test.ts, packages/models/src/lib/implementation/schemas.ts, packages/models/src/lib/implementation/schemas.unit.test.ts
Closes:
- code-pushup/portal#152
- code-pushup/portal#391
=> feat(models): allow non-integer audit values and ref weights

packages/plugin-coverage/src/lib/runner/index.ts, packages/plugin-coverage/src/lib/runner/runner.integration.test.ts, packages/plugin-eslint/src/lib/__snapshots__/eslint-plugin.integration.test.ts.snap, packages/plugin-eslint/src/lib/runner/index.ts, packages/plugin-eslint/src/lib/runner/lint.ts, packages/plugin-eslint/src/lib/runner/lint.unit.test.ts, packages/plugin-js-packages/src/lib/runner/index.ts, packages/plugin-js-packages/src/lib/runner/runner.integration.test.ts, packages/utils/src/index.ts, packages/utils/src/lib/file-system.ts, packages/utils/src/lib/file-system.unit.test.ts
=> fix: wrap paths in quotes in case of spaces

packages/cli/src/lib/implementation/only-plugins.middleware.ts, packages/cli/src/lib/implementation/only-plugins.middleware.unit.test.ts
=> feat(cli): adopt logic to forward plugins and categories if onlyPlugins is invalid

e2e/cli-e2e/tests/__snapshots__/compare.report-diff.md, packages/utils/src/lib/reports/__snapshots__/report-diff-added.md, packages/utils/src/lib/reports/__snapshots__/report-diff-improved.md, packages/utils/src/lib/reports/__snapshots__/report-diff-minimal.md, packages/utils/src/lib/reports/__snapshots__/report-diff-mixed.md, packages/utils/src/lib/reports/__snapshots__/report-diff-unchanged.md, packages/utils/src/lib/reports/generate-md-reports-diff.ts
closes #696
related:
https://github.com/code-pushup/portal/issues/376
=> refactor(utils): switch score columns in comparison

packages/utils/src/lib/reports/__snapshots__/report-diff-unchanged.md, packages/utils/src/lib/reports/generate-md-reports-diff.ts
Fixes bug from https://github.com/code-pushup/cli/pull/724#discussion_r1668249084
Related issue: #696 
--- 
Example of bug: https://github.com/code-pushup/github-action/pull/36#issuecomment-2213549584
=> fix(utils): unchanged categories table markdown content

README.md
[Click here for preview](https://github.com/code-pushup/cli/tree/6897db17a5ad9d249dcd10996d82d4067150ba79?tab=readme-ov-file#-officially-supported-plugins)
=> docs: improve plugin descriptions and fix titles in readme

package-lock.json
Fixes failing [CI / Audit](https://github.com/code-pushup/cli/actions/runs/10386153554/job/28756808872) jobs.
Docs: https://github.com/advisories/GHSA-8hc4-vh64-cxmj
=> build: update axios via `npm audit fix`

README.md
Closes #751 
- **Merged Columns**: Combine the plugin name and description into a single column for a more streamlined layout.
- **Table Header Update**: Introduce content for a table header row, which now enforces a minimum width for the columns, preventing icons from shrinking on smaller screens.
<details>
<summary>Smartphone</summary>
<p>Before:</p>
<p>After:</p>
</details>
<details>
<summary>Desktop</summary>
<p>Before:</p>
<p>After:</p>
</details>
=> docs: prevent plugin icons shrinking

.github/workflows/ci.yml, e2e/cli-e2e/project.json, e2e/create-cli-e2e/tests/init.e2e.test.ts, e2e/create-cli-e2e/vite.config.e2e.ts, tools/src/npm/npm.plugin.ts, tools/src/npm/utils.ts
Run old E2E last. Make install ordered
=> test: refactor e2e order to temporary fix testing

package.json
See [#919 ](https://github.com/code-pushup/cli/issues/919)
=> fix: fix poppinss version
