code-pushup/cli

nx.json
packages/cli/.eslintrc.json
packages/models/.eslintrc.json
packages/plugin-eslint/.eslintrc.json
packages/plugin-lighthouse/.eslintrc.json
packages/utils/.eslintrc.json

Workaround with `ignoredDependencies` for `@nx/dependency-checks` ESLint rule is now no longer needed :slightly_smiling_face:

build: fix dependency-checks rule - ignore vite.config.ts and *.mocks.ts

---

.github/ISSUE_TEMPLATE/bug_report.md
global-setup.ts
package-lock.json
packages/cli/src/lib/collect/command-object.spec.ts
packages/cli/src/lib/collect/command-object.ts
packages/cli/vite.config.ts
packages/models/test/schema.mock.ts
packages/models/test/test-data/config-and-report-dummy.mock.ts
packages/models/vite.config.ts
packages/plugin-eslint/vite.config.ts
packages/plugin-lighthouse/vite.config.ts
packages/utils/package.json
packages/utils/src/lib/collect/implementation/execute-process.spec.ts
packages/utils/src/lib/collect/implementation/mock/execute-process.mock.mjs
packages/utils/src/lib/collect/implementation/mock/process-helper.mock.ts
packages/utils/src/lib/collect/implementation/persist.spec.ts
packages/utils/src/lib/collect/implementation/utils.ts
packages/utils/src/lib/collect/index.spec.ts
packages/utils/src/lib/collect/index.ts
packages/utils/vite.config.ts
tsconfig.base.json
vitest.workspace.ts

Closes #71 
Unit tests for `cli` and `utils` packages were repeatedly failing locally, and some tests were even failing or passing seemingly at random. So I identified some sources of flakiness which I was able to eliminate to make unit tests pass repeatedly, even when run in parallel.
- reading `package.json` via `fs` made it unreliable because of relative path mismatch between `src` and `dist`
- replaced with a static `import`
- the same `out-execute-plugin.json` file was being created by many different tests, so some test results depended on which test ran before
- randomized the file name so that each test works with a different file
- also moved files into `.gitignore`d `tmp` directory so that tests don't generate untracked files
- test results also differed based on if project …

test: reduce unit test flakiness

---

examples/cli-e2e/mocks/config.mock.js
examples/cli-e2e/mocks/config.mock.mjs
examples/cli-e2e/mocks/config.mock.ts
examples/cli-e2e/tests/cli.spec.ts
examples/cli-e2e/vite.config.ts
package-lock.json
package.json
packages/cli/src/lib/collect/_command-object-config.mock.js
packages/cli/src/lib/collect/command-object.spec.ts
packages/cli/src/lib/implementation/mock/cli-config.mock.js
packages/cli/src/lib/implementation/mock/config-middleware-config.mock.js
packages/models/test/index.ts
packages/models/test/memfs.ts
packages/models/test/schema.mock.spec.ts
packages/models/test/schema.mock.ts
packages/models/test/test-data/config-and-report-dummy.mock.ts
packages/models/test/test-data/config-and-report-lighthouse.mock.ts
packages/models/test/test-data/config-and-report-nx-validators.mock.ts
packages/plugin-eslint/project.json
packages/plugin-eslint/src/lib/eslint-plugin.ts
packages/plugin-lighthouse/project.json
packages/plugin-lighthouse/src/lib/lighthouse-plugin.ts
packages/utils/src/lib/collect/implementation/execute-plugin.spec.ts
packages/utils/src/lib/collect/implementation/execute-process.spec.ts
packages/utils/src/lib/collect/implementation/mock/process-helper.mock.ts
packages/utils/src/lib/collect/implementation/mock/schema-helper.mock.ts
packages/utils/src/lib/collect/implementation/persist.spec.ts

Closes #72 
- no NPM workspaces
- E2E tests import from `dist` for now, should be solved properly by #33  
- using `.rejects.toThrowError()` instead of `.catch`
- using `node` (prerequisite) instead of `bash` (relies on UNIX) to create test files
- using `memfs` instead of actual file system for some tests 
Unfortunately, I wasn't able to come up with a way to mock `process.exit` in `cli` tests (`vi.spyOn(process, 'exit')` and other variants had no effect for some reason :confused:).

test: unit test improvements

---

packages/cli/project.json

I was missing a clear way to "try out" the CLI with something that's expected to work. Replaced `cli:exec` with `cli:run-help`, `cli:run-collect` and `cli:run-print-config`. The new targets use the example app instead of the mocked config.

chore(cli): custom targets to simplify manual testing

---

.github/workflows/ci.yml
e2e/cli-e2e/vite.config.ts

In this PR, I add matrix for running both unit and E2E tests on all three major platforms (Linux, Windows, MacOS).
- All jobs should run in parallel, so having all three platforms covered should not have any drawbacks.
- Even if one job fails, the other tests are executed.
- Timeout for E2E is increased due to slower execution in pipelines (mainly Windows).
- Unfortunately, the tests are currently flaky. I added one retry until this issue is resolved.

ci(testing): run tests on all major platforms

---

packages/cli/src/lib/yargs-cli.spec.ts
packages/cli/test/cli-parsing.config.mock.ts

In this PR, I fixed the following:
- The score was transformed to 0-1 range
- JSON formatting was handled for Linux via `echoRunnerConfig`
- I removed metadata fields which caused type inconsistencies

test(cli): fix progress bar config

---

commitlint.config.js
package-lock.json
package.json

I researched different plugins for commitlint as the current one produced false positives.
The `commitlint-plugin-tense` has the `firstOnly` option and a better recognition of nouns and adjectives that sound like verbs.
Docs [here](https://github.com/actuallydamo/commitlint-plugin-tense).

chore: apply different commitlint plugin for imperative tense

---

packages/plugin-eslint/src/lib/meta/groups.ts
packages/utils/src/lib/report-to-md.ts

PRs #196 and #201 were merged just before #198, which is why the lint errors weren't caught by CI.
[Failing lint job](https://github.com/flowup/quality-metrics-cli/actions/runs/6770668535/job/18400058371).

refactor: fix lint errors

---

.eslintrc.json
package-lock.json
package.json

Added the following rules from [esling-plugin-n](https://github.com/eslint-community/eslint-plugin-n#readme):
- [no-sync](https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/no-sync.md) - 27 warnings (see screenshot) :arrow_right: disabled in `lint` for now, but will be tracked by Code PushUp
- arguments for always using promises with `fs`:
- non-blocking - e.g. if we have a spinner in the terminal, then it should be smooth regardless of what file operations are happening
- easier to parallelize (`Promise.all`, `Promise.allSettled`)
- we have top-level await thanks to ESM, all tests and hooks can be `async` ... we don't really have a reason to use the sync version
- [prefer-promises/fs](https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/prefer …

build: add lint rules from eslint-plugin-n, disable no-sync temporarily

---

packages/utils/src/index.ts
packages/utils/src/lib/report-to-md.ts
packages/utils/src/lib/report-to-stdout.ts
packages/utils/src/lib/report.spec.ts
packages/utils/src/lib/report.ts
packages/utils/src/lib/utils.spec.ts
packages/utils/src/lib/utils.ts

This PR moves report related logic and moves `slugify` back into `utils.ts`. This file will undergo more refactoring in followup PRs.
There is on open ticket for this PR, but the scope is tiny and the change is very reasonable to to now.

refactor(utils): relocate report logic

---

e2e/cli-e2e/tests/collect.spec.ts
package-lock.json
package.json
packages/core/src/lib/implementation/persist.spec.ts
packages/core/src/lib/implementation/persist.ts
packages/utils/package.json
packages/utils/src/index.ts
packages/utils/src/lib/__snapshots__/report-to-md.spec.ts.snap
packages/utils/src/lib/__snapshots__/report-to-stdout.spec.ts.snap
packages/utils/src/lib/report-to-stdout.spec.ts
packages/utils/src/lib/report-to-stdout.ts
packages/utils/src/lib/report.ts

feat(utils): implement a new design for stdout

---

packages/core/src/lib/implementation/read-code-pushup-config.spec.ts
packages/core/test/invaid.config.mjs
packages/core/test/minimal.config.mjs
packages/models/src/lib/category-config.spec.ts
packages/models/test/fixtures/categories.mock.ts
packages/models/test/index.ts
packages/utils/src/lib/load-file.spec.ts
packages/utils/src/lib/load-file.ts
packages/utils/test/fixtures/undefined-export.mjs
packages/utils/test/fixtures/valid-export.mjs

refactor(core): improve report loading

---

.github/workflows/ci.yml
.github/workflows/code-coverage.yml
package-lock.json
package.json
packages/cli/project.json
packages/core/project.json
packages/models/project.json
packages/plugin-eslint/project.json
packages/utils/project.json

Closes #169 
In this PR, I set up the code coverage to run in our pipelines.
- Coverage results can be displayed by adding `--coverage` to any test `nx` command (was already working).
- I included coverage output in logs of every CI run (e.g. [here](https://github.com/code-pushup/cli/actions/runs/6893655166/job/18753721481?pr=278)).
- I set up [Codecov](https://about.codecov.io/) for our organisation (currently waiting for integration approval by an organisation owner).
- I created a separate pipeline taking results from all `nx` libraries to upload them and hopefully create a badge.
- The deprecated vitest coverage package [c8](https://www.npmjs.com/package/@vitest/coverage-c8) package was replaced by v8.

ci(workflows): set up code coverage

---

e2e/cli-e2e/tests/__snapshots__/help.spec.ts.snap
e2e/cli-e2e/tests/print-config.spec.ts
packages/cli/src/lib/autorun/command-object.ts
packages/cli/src/lib/collect/command-object.ts
packages/cli/src/lib/implementation/config-middleware.spec.ts
packages/cli/src/lib/implementation/config-middleware.ts
packages/cli/src/lib/implementation/filter-kebab-case-keys.spec.ts
packages/cli/src/lib/implementation/filter-kebab-case-keys.ts
packages/cli/src/lib/implementation/only-config-option.ts
packages/cli/src/lib/implementation/only-plugins-options.ts
packages/cli/src/lib/print-config/command-object.ts

Close #119
I modified `configMiddleware` and filtered all plugins. This allowed us not to modify the commands.

feat(cli): introduce the `onlyPlugins` option

---

package-lock.json
package.json
packages/utils/package.json
packages/utils/src/lib/__snapshots__/report-to-stdout.spec.ts.snap
packages/utils/src/lib/report-to-stdout.ts

`cliui` has the [issue](https://github.com/yargs/cliui/issues/89) with text wraping. `@isaacs/cliui` does not have it for now

fix(cli): replace clui on @isaacs/cliui

---

packages/utils/vite.config.integration.ts
packages/utils/vite.config.unit.ts

In this PR, I remove the E2E global setup for `utils` integration tests.
Additionally, I remove unnecessary comments which I forgot to remove in my previous PR.

test(utils): fix global setup and remove comments

---

.eslintrc.json

So that we can catch mistakes like this:
Context: https://github.com/code-pushup/cli/pull/275#discussion_r1401776075

build: lint .spec.ts files to report filename errors

---

commitlint.config.js

Now, `commitlint` will accept `release` as a type for commit messages along with the previously existing types, allowing more specific categorization of release commits. This change doesn't affect any existing functionality but extends the types that can be used for commit messages.
`release` was added for release actions after merging in the main.

ci: add custom `release` type to commitlint configuration

---

.github/workflows/release.yml

After merging PR in the main, the release job starts. In the release job, version tasks start with Nx. Nx, by default, starts tasks with `parallel=3`. This is a reason for the release job failing. 
[Here is a failing pipeline](https://github.com/code-pushup/cli/actions/runs/6978138664/job/18989026545)
```
[plugin-eslint] 🟠 No previous version tag found, fallback to version 0.0.0.
New version will be calculated based on all changes since first commit.
If your project is already versioned, please tag the latest release commit with plugin-eslint@x.y.z and run this command again.
[plugin-eslint] 🆕 Calculated new version "0.1.0".
[plugin-eslint] 📜 Generated CHANGELOG.md.
[plugin-eslint] 📝 Updated package.json version.
[plugin-eslint] ❌ Error: packages/core/CHANGELOG.md 121ms …
```

ci: disable parallel version task execution

---

.github/workflows/release.yml

Add write permission for the release workflow to fix tag pushing ([failed job](https://github.com/code-pushup/cli/actions/runs/6995824898/job/19031044372))

ci: update GitHub workflow permissions to create tag

---

nx.json
package-lock.json
package.json
packages/cli/project.json
packages/core/project.json
packages/models/project.json
packages/nx-plugin/project.json
packages/plugin-eslint/project.json
packages/plugin-lighthouse/project.json
packages/utils/project.json

- remove the `dependsOn` and `inputs` options for the `version` target. It's unnecessary here.
- change the `preset` option to `angular`. If `preset` is like an object, it must be a whole `preset` config with functions. It is not possible to set it in JSON format. We may need to create a preset package in a separate repo.
- move the `postTargets` options to `targetDefaults`.
- replace the `notesFile` option with `notes`. `notesFile` sent the whole `changelog` file to the single release.
All tests I did in [my test repo](https://github.com/IKatsuba/test-nx-semver)

ci: fix and simplify `version` and `github` configurations

---

packages/cli/mocks/constants.ts
packages/cli/src/lib/autorun/autorun-command.unit.test.ts
packages/cli/src/lib/collect/collect-command.unit.test.ts
packages/cli/src/lib/implementation/only-plugins-utils.unit.test.ts
packages/cli/src/lib/print-config/print-config-command.unit.test.ts
packages/cli/src/lib/upload/upload-command.unit.test.ts
packages/cli/src/lib/yargs-cli.ts
packages/cli/vite.config.integration.ts
packages/cli/vite.config.unit.ts
testing-utils/src/lib/setup/bundle-require.mock.ts
testing-utils/src/lib/setup/console-log.mock.ts
testing-utils/src/lib/setup/fs.mock.ts
testing-utils/src/lib/setup/portal-client.mock.ts
testing-utils/src/lib/setup/reset.mocks.ts

Closes #211 
In this PR, I extract and configure mock setup for the CLI package:
- unnecessary global setup is removed from both CLI integration and unit tests
- `fs` and `fs/promises` used in almost all unit tests.
- `console.log` is now mocked for all unit tests.
- `bundleRequire` used by command objects is also extracted.
- `portal-client`, while used by two command objects, is also extracted as it could be reused.
- I also reset mocks and `memfs` volume before each test.
Additionally, for better debugging, I disabled `exitProcess` in `yargsCli` which closes #243

test(cli): set up mocks, disable exit process for tests

---

packages/utils/src/lib/report-to-md.ts
packages/utils/src/lib/report.ts
packages/utils/src/lib/report.unit.test.ts

Added sorting of audit issues for `report.md`:
- by severity (errors first), 
- by source file (alphabetical),
- by start line (ascending).
Closes #313

feat(utils): add sorting of audit issues for report md

---

CONTRIBUTORS.md
README.md
packages/cli/README.md

docs(cli): add shortcuts to header section, created contributors.md

---

esbuild.config.js
package.json

For every `packages/*/package.json` file except `packages/test-utils/package.json`, add the following metadata as part of the build process
- License (MIT)
- Homepage (currently the readme in the GitHub repo)
- Bug tracker (GitHub Issues)
- Git repo and sub-directory for the individual package
- Contributors (@matejchalk, @BioPhoton, @Tlacenka, @MishaSeredenkoPushBased, @IKatsuba)
This metadata is copied from the root `package.json` file via our `PackageJSON` ESBuild plugin and shows up on npm pages like https://www.npmjs.com/package/@code-pushup/cli

chore: add package metadata

---

packages/plugin-eslint/src/lib/nx/utils.ts

Follow-up to:
- #384 
Should solve `Error: 'filePath' should not be a directory path.` :crossed_fingers:

fix(plugin-eslint): fix default Nx lint patterns - directory not valid for "files" in eslintrc

---

.env.example
.eslintrc.json
.github/workflows/ci.yml
CONTRIBUTING.md
CONTRIBUTORS.md
README.md
code-pushup.config.ts
esbuild.config.js
examples/plugins/.eslintrc.json
examples/plugins/code-pushup.config.ts
examples/plugins/project.json
examples/plugins/src/file-size/src/file-size.plugin.ts
examples/plugins/src/file-size/src/file-size.plugin.unit.test.ts
examples/plugins/src/package-json/src/integration/dependencies.audit.ts
examples/plugins/src/package-json/src/integration/type.audit.ts
examples/plugins/src/package-json/src/integration/utils.ts
examples/plugins/src/package-json/src/package-json.plugin.ts
examples/plugins/tsconfig.lib.json
examples/react-todos-app/project.json
project.json
testing-utils/package.json

Cleaned up the `examples-plugins` Nx project, in order to improve DX and bring it more in line with Nx conventions.
- No longer imports from `.../dist/packages/utils` in `src` folder, tests and lint targets no longer depend on `build`.
- No longer ignores the `@nx/enforce-module-boundaries` rule.
Made some other related improvements:
- Added custom targets to root project for running Code PushUp command on the whole repo (e.g. `npx nx run-collect`), automatically builds dependencies using `dependsOn`. 
- ESBuild config supports non-publishable libraries - creates minimal `package.json` automatically, includes necessary metadata so imports from `dist` work correctly (e.g. references correct type declarations).
- Removed `package.json` from `testing-utils` - it only needs to be buildable …

refactor(examples-plugins): optimize Nx project configuration

---

code-pushup.config.ts
examples/plugins/src/package-json/README.md
examples/plugins/src/package-json/src/integration/license.audit.ts
examples/plugins/src/package-json/src/integration/type.audit.ts
project.json

#397 should be merged before this PR.
Closes #390 
Since the custom plugins have been added to our Code PushUp config, meaningful audits (ESLint) are now intermingled with random audits (from custom plugins) which measure things that aren't meaningful for our repository.
- 50% of the Bug prevention score is made up of an audit which requires every package directly depends on Zod version `^3.22.4` (all but one fail). The 106 ESLint problems in total only impact the other 50% of the score. Hence why the score dropped massively from 84 to 50.
- The weight is ridiculous. The dependency audit shouldn't be 106x more impactful than each ESLint rule.
- The assertion is nonsense. Why should every package directly depend on Zod? It shouldn't. And why `^3.22.4` (`models` package fails with …

ci: meaningful categories configuration

---

.github/workflows/release.yml

Forgot to update `release.yml` in #397 :facepalm: 
[Example of failing step](https://github.com/code-pushup/cli/actions/runs/7472201046/job/20333895343)

ci: fix Code PushUp step in release pipeline

---

packages/core/.eslintrc.json
packages/core/src/lib/implementation/execute-plugin.unit.test.ts
packages/core/src/lib/implementation/persist.ts
packages/core/src/lib/implementation/persist.unit.test.ts
packages/core/src/lib/implementation/read-code-pushup-config.integration.test.ts
packages/core/src/lib/implementation/runner.ts
packages/core/src/lib/implementation/runner.unit.test.ts
packages/plugin-eslint/.eslintrc.json
packages/plugin-eslint/src/lib/eslint-plugin.integration.test.ts
packages/plugin-eslint/src/lib/eslint-plugin.ts
packages/plugin-eslint/src/lib/meta/hash.ts
packages/plugin-eslint/src/lib/meta/hash.unit.test.ts
packages/plugin-eslint/src/lib/meta/rules.unit.test.ts
packages/plugin-eslint/src/lib/nx.integration.test.ts
packages/plugin-eslint/src/lib/runner.integration.test.ts
packages/plugin-eslint/src/lib/runner/index.ts
packages/utils/.eslintrc.json
packages/utils/perf/crawl-file-system/index.ts
packages/utils/src/lib/execute-process.ts
packages/utils/src/lib/execute-process.unit.test.ts
packages/utils/src/lib/file-system.ts
packages/utils/src/lib/file-system.unit.test.ts
packages/utils/src/lib/formatting.ts
packages/utils/src/lib/formatting.unit.test.ts
packages/utils/src/lib/git.integration.test.ts
packages/utils/src/lib/log-results.unit.test.ts
packages/utils/src/lib/progress.integration.test.ts
packages/utils/src/lib/report.ts
packages/utils/src/lib/report.unit.test.ts
testing-utils/src/lib/fixtures/report.mock.ts

I went through the report and removed most ESLint related issues in test files and enabled rules where possible.
There are still ESLint issues in models (I will deal with those during my test refactor), nx-plugin (not relevant atm) and a few waiting for the rule to be enabled (so that I can disable the ESLint for that line)
Before: 189 errors, 364 warnings, 10 info
After: 183 errors, 271 warnings, 10 info
Link to report displayed in portal [here](https://quality-metrics-staging.web.app/portal/code-pushup/cli/branch/fix-eslint-in-test-files/dashboard).

chore: remove ESLint issues from test files in core, plugin-eslint and utils

---

.github/workflows/pr-labeler.yml

As PR's from forks fail (see #381) we need to adopt the trigger for `pull_request` to `pull_request_target`.
Docs can be found here: https://github.com/actions/labeler#permissions

ci: fix labeler workflow for prs from fork

---

packages/cli/.eslintrc.json
packages/cli/src/index.ts
packages/cli/src/lib/autorun/autorun-command.ts
packages/cli/src/lib/cli.ts
packages/cli/src/lib/collect/collect-command.ts
packages/cli/src/lib/constants.ts
packages/cli/src/lib/implementation/config-middleware.ts
packages/cli/src/lib/implementation/filter-kebab-case-keys.ts
packages/cli/src/lib/implementation/model.ts
packages/cli/src/lib/implementation/utils.ts
packages/cli/src/lib/upload/upload-command.ts
packages/cli/src/lib/yargs-cli.integration.test.ts
packages/cli/src/lib/yargs-cli.ts

In this PR I focused on enabling ESLint rules, so that they can be used both for production and test code:
- I fixed most ESLint issues.
- I improved implementation or notation where applicable.
- I disabled ESLint where necessary.
Before: 
[After](https://quality-metrics-staging.web.app/portal/code-pushup/cli/branch/eslint-cli-fixes/dashboard):

chore(cli): fix most ESLint issues

---

e2e/cli-e2e/tests/collect.e2e.test.ts
packages/cli/src/lib/yargs-cli.integration.test.ts
packages/cli/src/lib/yargs-cli.ts
packages/core/.eslintrc.json
packages/core/src/lib/collect-and-persist.ts
packages/core/src/lib/implementation/collect.integration.test.ts
packages/core/src/lib/implementation/collect.ts
packages/core/src/lib/implementation/execute-plugin.ts
packages/core/src/lib/implementation/execute-plugin.unit.test.ts
packages/core/src/lib/implementation/json-to-gql.ts
packages/core/src/lib/implementation/json-to-gql.unit.test.ts
packages/core/src/lib/implementation/persist.ts
packages/core/src/lib/implementation/runner.ts
packages/core/src/lib/implementation/runner.unit.test.ts
packages/core/src/lib/upload.ts
packages/utils/src/index.ts
packages/utils/src/lib/file-system.ts
testing-utils/src/lib/utils/minimal-config.mock.ts
testing-utils/src/lib/utils/report.mock.ts

In this PR, I attempted to resolve ESLint issues in the `core` package. Currently, only one rule is turned off due to type inconsistencies encountered both in `cli` and `core` that is raised in a separate issue #411.
Notable changes:
- Since `exists` is deprecated, I had to use `stat` with an additional directory check and extracted the function to `utils`.
- Aside from ESLint issues, I added validation for `persist.format` during `yargs` parsing in order to prevent invalid values being passed as an incorrect type throughout the CLI flow.
Before:
[After](https://quality-metrics-staging.web.app/portal/code-pushup/cli/branch/eslint-core-fixes/dashboard):

chore: fix core ESLint issues, validate persist.format values in CLI

---

packages/cli/README.md
packages/cli/docs/custom-plugins.md

Slight improvements for the custom plugin section of the cli docs.
More feedback for the custom-plugin detail page:
Instead of using `MyAudit`, use something actually meaningful. Also add a minimal example in the very beginning of the docs section, where you describe that you can basically implement "anything". Maybe you can specify "anything" with an actual example.

docs: improve custom plugin docs

---

.eslintrc.json
packages/utils/.eslintrc.json
packages/utils/perf/crawl-file-system/index.ts
packages/utils/perf/score-report/index.ts
packages/utils/perf/score-report/optimized0.ts
packages/utils/perf/score-report/optimized1.ts
packages/utils/perf/score-report/optimized2.ts
packages/utils/perf/score-report/optimized3.ts
packages/utils/src/lib/execute-process.ts
packages/utils/src/lib/file-system.ts
packages/utils/src/lib/formatting.ts
packages/utils/src/lib/log-results.ts
packages/utils/src/lib/progress.ts
packages/utils/src/lib/reports/__snapshots__/sorting.integration.test.ts.snap
packages/utils/src/lib/reports/constants.ts
packages/utils/src/lib/reports/generate-md-report.ts
packages/utils/src/lib/reports/generate-stdout-summary.ts
packages/utils/src/lib/reports/md/headline.ts
packages/utils/src/lib/reports/md/table.ts
packages/utils/src/lib/reports/scoring.ts
packages/utils/src/lib/reports/sorting.ts
packages/utils/src/lib/reports/utils.ts
packages/utils/src/lib/transform.ts

Closes #261 
Closes #270 
This PR is part 1 of utils ESLint issues. I mostly fixed unicorn and sonarjs issues.
I also loosened ruleset for `perf` folder as its nature is more experimental.
Before:
[After](https://quality-metrics-staging.web.app/portal/code-pushup/cli/branch/eslint-utils-fixes/dashboard):

chore(utils): fix ESLint issues, loosen perf ESLint rules

---

testing-utils/src/lib/setup/console.mock.ts

Related to #357 
I prevented console from logging into our test outputs.
Note: I found out one output that still appears - directly from `bundle-require`. Not sure why.
Before:
After:

test: prevent console logging in test output

---

packages/utils/.eslintrc.json
packages/utils/perf/crawl-file-system/index.ts
packages/utils/perf/score-report/index.ts
packages/utils/perf/score-report/optimized0.ts
packages/utils/perf/score-report/optimized1.ts
packages/utils/perf/score-report/optimized2.ts
packages/utils/perf/score-report/optimized3.ts
packages/utils/src/lib/execute-process.ts
packages/utils/src/lib/file-system.ts
packages/utils/src/lib/formatting.ts
packages/utils/src/lib/git.ts
packages/utils/src/lib/group-by-status.ts
packages/utils/src/lib/reports/generate-md-report.ts
packages/utils/src/lib/reports/generate-stdout-summary.ts
packages/utils/src/lib/reports/md/table.ts
packages/utils/src/lib/reports/scoring.ts
packages/utils/src/lib/reports/sorting.ts
packages/utils/src/lib/reports/utils.ts
packages/utils/src/lib/reports/utils.unit.test.ts
packages/utils/src/lib/transform.ts

Closes #265 
Closes #267 
Closes #268 
Closes #269 
Closes #271 
In this PR, I tackle the rest of the ESLint issues in `utils`. Notable changes and findings:
- Again, I was not able to resolve `no-unnecessary-condition` due to #421
- In perf files, some of the types are wrong. For the sake of its experimental nature, however, I opted to disable ESLint rules instead. Relevant notes were added there.
- There is one case where I hesitated - replacing `pop` with `slice`. Should I leave it or not? 🙏 
Before:
[After](https://quality-metrics-staging.web.app/portal/code-pushup/cli/branch/eslint-utils-fixes-vol2/dashboard):

chore(utils): fix ESLint issues, enable ESLint rules

---

package-lock.json
package.json
packages/core/package.json
packages/core/src/lib/upload.ts
packages/models/package.json
packages/models/src/lib/upload-config.ts

Long-running upload requests are unlikely to ever resolve past a certain interval. To prevent hanging CI jobs (which cost money), a default timeout of 5 minutes is set (in `@code-pushup/portal-client` - see https://github.com/code-pushup/portal/pull/230) after which upload will fail. This value is customizable via `upload.timeout` in config file.

feat(core): add upload timeout

---

packages/utils/src/lib/formatting.ts
packages/utils/src/lib/formatting.unit.test.ts
packages/utils/src/lib/reports/__snapshots__/generate-md-report.integration.test.ts.snap
packages/utils/src/lib/reports/generate-md-report.ts

fix(utils): set fixed locale for date in report.md

---

packages/utils/src/lib/reports/utils.unit.test.ts

Part of #272.
- Add unit tests covering the internal function `formatReportScore` in `@code-pushup/utils`

test(utils): add unit tests covering `formatReportScore`

---

packages/utils/src/lib/reports/scoring.ts
packages/utils/src/lib/reports/scoring.unit.test.ts
packages/utils/src/lib/reports/utils.unit.test.ts

Until now the `calculatedScore` output value was only verified for division by 0. This meant that invalid values could get further into the report.
I added other checks that would make invalid references throw.

refactor(utils): check scoring prerequisites

---

packages/plugin-eslint/README.md

docs(plugin-eslint): adopt docs

---

.github/workflows/ci.yml
.github/workflows/release.yml

This PR fixes the release packages workflow by providing coverage results before running autorun.
Logs [here](https://github.com/code-pushup/cli/actions/runs/7782083778/job/21217772516).

chore(workflows): include unit test coverage in release packages for now

---

packages/utils/src/lib/execute-process.unit.test.ts

The `executeProcess` test was flaky due to environment-specific behaviour (pipelines vs local setup) where the `onStdout` spy was called once or twice (second call being with empty new line, see [here](https://github.com/code-pushup/cli/actions/runs/7785559898/job/21228444707)).
As a solution I removed the part of assertion demanding how many times the observer was called, leaving that it was called at least once and what its final value is. I think this is sufficient.

test(utils): adapt to different process stdout behaviour

---

examples/plugins/src/lighthouse/src/lighthouse.plugin.integration.test.ts

Currently, the pipelines are failing due to a very long lasting integration test (locally it takes roughly 25 seconds).
In this PR, I increased this timeout for windows pipelines which are known to take even longer.
A follow-up issue has been created to reduce the base test time. #490

chore(examples-plugins): increase lighthouse example plugin timeout

---

examples/plugins/src/lighthouse/src/lighthouse.plugin.integration.test.ts
packages/models/src/lib/audit.ts
packages/models/src/lib/audit.unit.test.ts
packages/models/src/lib/plugin-config.unit.test.ts
packages/models/src/lib/report.ts
packages/models/src/lib/report.unit.test.ts

closes #406
Notes: Additionally, I marked an example Lighthouse plugin to be ignored until #490 is complete due to pipeline timeouts.

refactor(models): require at least 1 plugin with at least 1 audit in config and report

---

package-lock.json
package.json
packages/models/package.json
packages/models/src/index.ts
packages/models/src/lib/implementation/schemas.ts

Pre-requisite for:
- #474 
Since we want to import `@code-pushup/portal-client` dynamically for uploads only, then we can no longer use it for validating material icons in plugin metadata. So I extracted it to a different package.
Package links:
- [NPM](https://www.npmjs.com/package/vscode-material-icons)
- [GitHub](https://github.com/matejchalk/vscode-material-icons)

refactor(models): import material icons from different package

---

e2e/cli-e2e/mocks/fixtures/code-pushup.config.coverage.ts
e2e/cli-e2e/tests/__snapshots__/collect.e2e.test.ts.snap
packages/plugin-coverage/README.md
packages/plugin-coverage/src/lib/config.ts
packages/plugin-coverage/src/lib/config.unit.test.ts
packages/plugin-coverage/src/lib/coverage-plugin.unit.test.ts
packages/plugin-coverage/src/lib/runner/lcov/__snapshots__/lcov-runner.integration.test.ts.snap
packages/plugin-coverage/src/lib/runner/lcov/lcov-runner.integration.test.ts
packages/plugin-coverage/src/lib/runner/lcov/lcov-runner.ts
packages/plugin-coverage/src/lib/runner/runner.integration.test.ts

Related to #430 
In this PR, I allow passing result paths as strings.
However, this approach **can be only used for a single project setup** atm as LCOV needs to prepend path to root in its records with relative paths.
Once another format is supported, the full potential along with globs will be unlocked. Created #498 for this.

feat(plugin-coverage): allow passing results as strings

---

global-setup.e2e.ts

In this PR, I fix the uninstallation step after E2E are run. Until now, the dependencies stayed in `node_modules` which broke running subsequent test (`@code-pushup/...` was used from the node modules instead of from dist I believe).
By omitting the `@e2e` during uninstall, all dependencies are now correctly uninstalled.

test(cli-e2e): fix uninstallation of dependencies in E2E teardown

---

e2e/cli-e2e/tests/__snapshots__/collect.e2e.test.ts.snap
examples/plugins/vite.config.integration.ts
examples/plugins/vite.config.unit.ts
examples/react-todos-app/project.json
packages/cli/docs/custom-plugins.md
packages/cli/vite.config.unit.ts
packages/core/src/lib/implementation/execute-plugin.ts
packages/core/src/lib/normalize.ts
packages/core/vite.config.unit.ts
packages/plugin-coverage/src/lib/runner/lcov/lcov-runner.integration.test.ts
packages/plugin-coverage/src/lib/runner/lcov/transform.ts
packages/plugin-eslint/src/lib/__snapshots__/runner.integration.test.ts.snap
packages/plugin-eslint/src/lib/runner.integration.test.ts
packages/plugin-eslint/src/lib/runner/lint.ts
packages/plugin-eslint/src/lib/runner/lint.unit.test.ts
packages/plugin-eslint/src/lib/runner/transform.ts
packages/plugin-eslint/src/lib/runner/transform.unit.test.ts
packages/plugin-eslint/src/lib/runner/types.ts
packages/utils/src/index.ts
packages/utils/src/lib/git.integration.test.ts
packages/utils/src/lib/git.ts
packages/utils/src/lib/transform.ts
packages/utils/src/lib/transform.unit.test.ts
testing-utils/src/index.ts
testing-utils/src/lib/setup/git.mock.ts
testing-utils/src/lib/utils/os-agnostic-paths.ts

Fixes #465 
Removed all usages of `toUnixPath` in plugins. Since it would be inconvenient to use the new helper function in each plugin - it's now async and we don't want to run the Git command for each issue - I transferred that responsibility to `core`. Created testing utils for making paths OS-agnostic for snapshot tests. And refactored Git tests to run against a temporary git repo (I recommend applying this approach to #469).

feat(core): make all issue file paths relative to git root after executing plugin

---

testing/test-utils/project.json

The coverage folder was not properly defined for `test-utils`. Fixed here.

test: fix reportsDirectory for test-utils

---

package-lock.json
package.json
packages/utils/perf/crawl-file-system/fs-walk.ts
packages/utils/perf/crawl-file-system/optimized0.ts
packages/utils/perf/glob/fast-glob.ts
packages/utils/perf/glob/glob.ts
packages/utils/perf/glob/globby.ts
packages/utils/perf/glob/index.ts

This PR includes perf benchmarks for:
- file system crawling
- [@nodelib/fs.walk](https://www.npmjs.com/package/@nodelib/fs.walk)
- glob search libs
- [fast-glob](https://www.npmjs.com/package/fast-glob)
- [glob](https://www.npmjs.com/package/glob)
- [globby](https://www.npmjs.com/package/globby)
---
**file system crawling**  
```bash
> nx run utils:perf crawl-file-system
You can adjust the test with the following arguments:
directory      target directory of test      --directory=/Users/michael_hladky/WebstormProjects/quality-metrics-cli/node_modules
pattern        pattern to search             --pattern=/.json$/
Start benchmark...
Base x 2.43 ops/sec ±1.45% (17 runs sampled)
nodelib.fsWalk x 17.09 ops/sec ±0.74% (82 runs sampled)
Total Duration: 13.08 sec
Fastest is nodelib.fsWalk
``` …

perf(utils): add benchmarks for file system walk and glob libs

---

.github/workflows/ci.yml
esbuild.config.js

Fixes #493 
The problem was a misunderstanding in how `@nx/esbuild` interprets the `"esbuildConfig": "esbuild.config.js"` option. It's not meant to be [a build script as described in ESBuild docs](https://esbuild.github.io/getting-started/#build-scripts). It's only supposed to export additional ESBuild options (only way to define ESBuild plugins), the Nx executor [`require`s it under the hood](https://github.com/nrwl/nx/blob/17.1.3/packages/esbuild/src/executors/esbuild/lib/normalize.ts#L44-L54). The Nx executor also [copies the source `package.json` to `dist` output](https://github.com/nrwl/nx/blob/17.1.3/packages/esbuild/src/executors/esbuild/lib/normalize.ts#L15-L24), which was in a race condition with our custom `PackageJson` plugin triggered by calling `esbuild.build(...)` (which is …

build: fix race condition in build scripts

---

packages/plugin-eslint/src/lib/runner/transform.ts
packages/plugin-eslint/src/lib/runner/transform.unit.test.ts

Fixed validation error coming from [unicorn/no-abusive-eslint-disable](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-abusive-eslint-disable.md) rule - column 0 wasn't handled and failed validation.

fix(plugin-eslint): handle rules which emit column 0

---

packages/plugin-coverage/src/bin.ts
packages/plugin-coverage/src/lib/runner/index.ts
packages/plugin-eslint/src/bin.ts

Related to #497 
Until now, the plugin failure was silent and ended up by failing during scoring the incomplete report (no Report parsing is done atm).
In this PR, I removed the `catch` which caused this behaviour in this PR so now the plugins fail after they are run.
I did not delve into the user experience of the logs (they are printed twice or three times still) in this PR, I only fixed the plugin fail behaviour.

fix: stop CLI when a plugin fails

---

.eslintignore

In this PR, I exclude fixtures from ESLint.
Our fixtures mostly contain static files such as configuration files but in ESLint plugin also include an example nx monorepo. Unfortunately, our ESLint finds its configuration and includes its ESLint issues in the [CLI report](https://quality-metrics-staging.web.app/portal/code-pushup/cli/commit/b2c87eb716a84f82b5d59e7238ffcae7147f707a/issues?categories=bug-prevention&categories=code-style).
After the change, the fixtures are [excluded ](https://quality-metrics-staging.web.app/portal/code-pushup/cli/branch/disable-eslint-example-repo/issues?categories=bug-prevention&categories=code-style)from the report.

chore: exclude fixtures from ESLint

---

packages/plugin-coverage/src/lib/runner/index.ts
packages/plugin-eslint/src/lib/__snapshots__/eslint-plugin.integration.test.ts.snap
packages/plugin-eslint/src/lib/config.ts
packages/plugin-eslint/src/lib/eslint-plugin.ts
packages/plugin-eslint/src/lib/runner.integration.test.ts
packages/plugin-eslint/src/lib/runner/index.ts

**WIP**
Closes #529 
In this PR, I rework the ESLint plugin to pass arguments to the runner via a configuration file.
When running the ESLint plugin locally now, the correct output is produced instead of `The command line is too long.`
<details>
<summary> Part of the output </summary>
</details>

fix(plugin-eslint): pass arguments via config file instead of argv

---

packages/plugin-eslint/src/lib/runner.integration.test.ts

In this PR, I include ESLint integration tests in our pipelines again.
Apparently, something that happened after the nx update fixed the encountered issues.

test(plugin-eslint): enable integration tests

---

e2e/cli-e2e/tests/collect.e2e.test.ts
packages/cli/src/lib/autorun/autorun-command.ts
packages/cli/src/lib/upload/upload-command.ts
packages/core/src/lib/collect-and-persist.unit.test.ts
packages/core/src/lib/implementation/collect.integration.test.ts
packages/core/src/lib/implementation/collect.ts
packages/core/src/lib/implementation/persist.ts
packages/core/src/lib/upload.ts
packages/models/docs/models-reference.md
packages/models/src/index.ts
packages/models/src/lib/commit.ts
packages/models/src/lib/commit.unit.test.ts
packages/models/src/lib/report.ts
packages/models/src/lib/report.unit.test.ts
packages/utils/src/index.ts
packages/utils/src/lib/git.integration.test.ts
packages/utils/src/lib/git.ts
packages/utils/src/lib/reports/__snapshots__/generate-md-report.integration.test.ts.snap
packages/utils/src/lib/reports/__snapshots__/sorting.integration.test.ts.snap
packages/utils/src/lib/reports/generate-md-report.integration.test.ts
packages/utils/src/lib/reports/generate-md-report.ts
testing/test-utils/src/lib/utils/dynamic-mocks/commit.mock.ts
testing/test-utils/src/lib/utils/dynamic-mocks/config.mock.ts
testing/test-utils/src/lib/utils/dynamic-mocks/report.mock.ts
testing/test-utils/src/lib/utils/report.mock.ts

Prerequisite for #482 
Instead of fetching the latest commit for `upload` command and `report.md` formatting, the commit is fetched and included in `report.json` by `collect`.

feat(cli): include commit info in report.json

---

.github/workflows/pr-commitlint.yml
.github/workflows/pr-labeler.yml

In order to match required checks better, I added names to labeler and commitlint jobs.

ci: improve pipeline naming

---

e2e/cli-e2e/tests/collect.e2e.test.ts
examples/react-todos-app/code-pushup.config.js
global-setup.e2e.ts
global-setup.ts
packages/utils/src/lib/git.integration.test.ts

In this PR, I unify the behaviour of test outputs:
- A test may create a `tmp` subfolder but should not expect `tmp` to be in place.
- A test should clean up after itself - delete a created `tmp` subfolder but not the `tmp` folder itself.
The whole strategy is documented in our [test strategy](https://github.com/code-pushup/cli/wiki/Testing-Strategy#test-outputs).

test: create subfolders under tmp for tests

---

examples/plugins/src/lighthouse/src/lighthouse.plugin.ts
examples/plugins/src/package-json/src/integration/utils.ts
packages/cli/src/lib/autorun/autorun-command.unit.test.ts
packages/cli/src/lib/implementation/core-config.integration.test.ts
packages/cli/src/lib/upload/upload-command.unit.test.ts
packages/cli/src/lib/yargs-cli.integration.test.ts
packages/core/src/lib/implementation/execute-plugin.ts
packages/core/src/lib/upload.unit.test.ts
packages/plugin-coverage/src/lib/config.unit.test.ts
packages/plugin-coverage/src/lib/runner/lcov/transform.unit.test.ts
packages/plugin-coverage/src/lib/runner/runner.integration.test.ts
packages/plugin-coverage/src/lib/utils.unit.test.ts
packages/plugin-eslint/src/lib/eslint-plugin.integration.test.ts
packages/plugin-eslint/src/lib/runner.integration.test.ts
packages/plugin-eslint/src/lib/runner/transform.unit.test.ts
packages/plugin-lighthouse/src/lib/utils.unit.test.ts
packages/utils/src/lib/reports/utils.unit.test.ts

Upon discovering one can use a type argument in `toEqual` and `toStrictEqual`, I added these arguments in our tests. They replace the need for `satisfies` in expected test output.
Note: The type argument cannot be used when the output from `expect` is a promise that requires a `resolves` first.

test: add type notation in tests

---

.github/CODEOWNERS
.github/labeler.yml
.github/workflows/code-coverage.yml
README.md
e2e/cli-e2e/project.json
packages/plugin-js-packages/.eslintrc.json
packages/plugin-js-packages/README.md
packages/plugin-js-packages/package.json
packages/plugin-js-packages/project.json
packages/plugin-js-packages/src/bin.ts
packages/plugin-js-packages/src/index.ts
packages/plugin-js-packages/src/lib/config.ts
packages/plugin-js-packages/src/lib/config.unit.test.ts
packages/plugin-js-packages/src/lib/constants.ts
packages/plugin-js-packages/src/lib/js-packages-plugin.ts
packages/plugin-js-packages/src/lib/js-packages-plugin.unit.test.ts
packages/plugin-js-packages/src/lib/runner/constants.ts
packages/plugin-js-packages/src/lib/runner/index.ts
packages/plugin-js-packages/src/lib/utils.ts
packages/plugin-js-packages/tsconfig.json
packages/plugin-js-packages/tsconfig.lib.json
packages/plugin-js-packages/tsconfig.test.json
packages/plugin-js-packages/vite.config.integration.ts
packages/plugin-js-packages/vite.config.unit.ts
project.json
tsconfig.base.json

Related to #542 
In this PR I do the following:
- Set up the plugin, its ESLint, dependencies, etc.
- Define plugin configuration schema.
- Create documentation.
Notes:
- Runner will follow in another PR.
- For now, all dependency groups are checked. Configurable dependency groups will be in post-MVP.
- Naming improvements are welcome!

feat(plugin-js-packages): set up and implement configuration for audit plugin

---

e2e/cli-e2e/tests/__snapshots__/compare.e2e.test.ts.snap
e2e/cli-e2e/tests/__snapshots__/help.e2e.test.ts.snap
e2e/cli-e2e/tests/compare.e2e.test.ts
packages/cli/README.md
packages/cli/src/lib/commands.ts
packages/cli/src/lib/compare/compare-command.ts
packages/cli/src/lib/compare/compare-command.unit.test.ts
packages/cli/src/lib/implementation/compare.model.ts
packages/cli/src/lib/implementation/compare.options.ts
packages/cli/src/lib/yargs-cli.integration.test.ts

feat(cli): implement compare command

---

code-pushup.config.ts
packages/plugin-js-packages/README.md
packages/plugin-js-packages/src/bin.ts
packages/plugin-js-packages/src/lib/config.ts
packages/plugin-js-packages/src/lib/constants.ts
packages/plugin-js-packages/src/lib/js-packages-plugin.ts
packages/plugin-js-packages/src/lib/runner/audit/constants.ts
packages/plugin-js-packages/src/lib/runner/audit/transform.ts
packages/plugin-js-packages/src/lib/runner/audit/transform.unit.test.ts
packages/plugin-js-packages/src/lib/runner/audit/types.ts
packages/plugin-js-packages/src/lib/runner/index.ts
packages/plugin-js-packages/src/lib/runner/outdated/constants.ts
packages/plugin-js-packages/src/lib/runner/outdated/transform.ts
packages/plugin-js-packages/src/lib/runner/outdated/transform.unit.test.ts
packages/plugin-js-packages/src/lib/runner/outdated/types.ts
packages/plugin-js-packages/src/lib/runner/runner.integration.test.ts
packages/utils/src/lib/execute-process.ts
packages/utils/src/lib/execute-process.unit.test.ts

Related to #542
In this PR, I implement the plugin runner for the packages plugin. Currently, it only supports `npm` package manager.
- I added `alwaysResolve` option to our `executeProcess` to suppress non-zero code from `npm outdated`.
- I added this plugin to our Code PushUp config, so that we can see `npm audit` and `npm outdated` results in portal.
- I added score calculation logic to the plugin documentation.
- Linking to dependency line in `package.json`.
- Configurable dependency groups.
- Attempting to get more vulnerability context via indirect reference to another dependency in `via` or `effects`.
- Mention all outdated versions in `outdated` display value.
<details>
<summary> Dashboard </summary>
</details>
<details>
<summary> Security detail</summary>
</details>
<details> …

feat(plugin-js-packages): implement npm audit and outdated runner

---

packages/plugin-coverage/src/lib/nx/coverage-paths.ts

In this PR, I do a mini clean-up:
- I remove a mysterious empty mock file from the `cli` package.
- I set logging for coverage plugin helper to `false` by default. This means no more extensive logs before the `collect` command including the [CI](https://github.com/code-pushup/cli/actions/runs/8331116281/job/22797264624?pr=572#step:5:18).

chore: remove verbose logs, unused mock

---

e2e/cli-e2e/tests/__snapshots__/compare.report-diff.md
packages/utils/src/lib/reports/__snapshots__/report-diff-added.md
packages/utils/src/lib/reports/__snapshots__/report-diff-improved.md
packages/utils/src/lib/reports/__snapshots__/report-diff-minimal.md
packages/utils/src/lib/reports/__snapshots__/report-diff-mixed.md
packages/utils/src/lib/reports/utils.ts

Turns out the triangle arrowhead unicode symbols (🠅 🠇) aren't supported on Apple devices (thanks to @BioPhoton for reporting), so used more common unicode symbol (↑ ↓) which should have better OS support.
<details>
<summary>iPhone screenshot</summary>
</details>
<details>
<summary>
screenshot of supported unicode arrows on Apple devices (http://xahlee.info/comp/unicode_arrows.html)</summary>
</details>
:arrow_down: The comment below isn't updated yet because `compare` runs in `main` branch :sweat_smile:

fix(utils): use unicode arrows with wider OS support

---

.gitignore
README.md

In this PR, I do the following:
- I change emojis for our packages to reflect their nature (📦 for our main CLI packages and 🧩 for plugins)
- I add `.npmrc` to `.gitignore`, so that I can store NPM credentials locally without `git` tracking them.

chore: improve docs, add npmrc to gitignore

---

packages/cli/vite.config.integration.ts
packages/cli/vite.config.unit.ts
packages/core/vite.config.integration.ts
packages/core/vite.config.unit.ts
packages/models/vite.config.integration.ts
packages/models/vite.config.unit.ts
packages/nx-plugin/vite.config.integration.ts
packages/nx-plugin/vite.config.unit.ts
packages/plugin-coverage/vite.config.integration.ts
packages/plugin-coverage/vite.config.unit.ts
packages/plugin-eslint/vite.config.integration.ts
packages/plugin-eslint/vite.config.unit.ts
packages/plugin-js-packages/vite.config.integration.ts
packages/plugin-js-packages/vite.config.unit.ts
packages/plugin-lighthouse/vite.config.integration.ts
packages/plugin-lighthouse/vite.config.unit.ts
packages/utils/vite.config.integration.ts
packages/utils/vite.config.unit.ts

I noticed that our coverage in Codecov is 79%. After looking at the files, I saw that `mocks` and `perf` folder were counted in.
In this PR, I explicitly exclude these folders as well as `zod2md` configuration file using [`coverage.exclude`](https://vitest.dev/config/#coverage-exclude).
[Before](https://app.codecov.io/gh/code-pushup/cli/tree/main/packages) (79%)
[After](https://app.codecov.io/gh/code-pushup/cli/tree/coverage-exclude/packages) (91%)

test: exclude mocks, perf and config from coverage

---

e2e/cli-e2e/tests/compare.e2e.test.ts
packages/utils/src/lib/reports/__snapshots__/report-diff-added.md
packages/utils/src/lib/reports/__snapshots__/report-diff-improved.md
packages/utils/src/lib/reports/__snapshots__/report-diff-minimal.md
packages/utils/src/lib/reports/__snapshots__/report-diff-mixed.md
packages/utils/src/lib/reports/__snapshots__/report-diff-unchanged.md
packages/utils/src/lib/reports/__snapshots__/report-no-categories.md
packages/utils/src/lib/reports/__snapshots__/report.md
packages/utils/src/lib/reports/generate-md-report.ts
packages/utils/src/lib/reports/generate-md-reports-diff.ts

Found out that plain commit hash in full is auto-linked by both GitHub (see [Autolinked references - Commit SHAs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#commit-shas)) and GitLab (see [GitLab-specific references](https://docs.gitlab.com/ee/user/markdown.html#gitlab-specific-references)).
Solves part of #149.
(The comment in this PR ran from `main`, so it still uses the old formatting.)

feat(utils): use auto-link commit format (GitHub/GitLab) in markdown

---

.github/workflows/code-coverage.yml
examples/plugins/vite.config.integration.ts
examples/plugins/vite.config.unit.ts

Closes #540 
As a follow-up of #583 , I also exclude non-production code from `examples-plugins`.
Codecov is [silently failing](https://app.codecov.io/gh/code-pushup/cli/commit/2f26c6c241dc1900fbf131cc9ae83618e7f4ffb3) while uploading the reports.
I am trying to follow their [example](https://github.com/codecov/codecov-action/tree/v4/?tab=readme-ov-file#example-workflowyml-with-codecov-action) exactly to rule out wonky file path support or similar.
As per usual, it works in for [this branch](https://app.codecov.io/gh/code-pushup/cli/tree/codecov-debug/packages). We will see though if it is going to work once merged to `main` (last time it did not). 🤞

test: exclude coverage from examples-plugins, update codecov workflow

---

.github/workflows/code-pushup.yml
code-pushup.config.ts

Closes #575 
Uses new [GitHub Action](https://github.com/marketplace/actions/code-pushup) :rocket:

ci: use code-pushup/github-action

---

packages/plugin-js-packages/README.md
packages/plugin-js-packages/src/lib/js-packages-plugin.ts
packages/plugin-js-packages/src/lib/js-packages-plugin.unit.test.ts
packages/plugin-js-packages/src/lib/runner/audit/constants.ts
packages/plugin-js-packages/src/lib/runner/audit/transform.ts
packages/plugin-js-packages/src/lib/runner/audit/types.ts
packages/plugin-js-packages/src/lib/runner/audit/unify-type.ts
packages/plugin-js-packages/src/lib/runner/audit/unify-type.unit.test.ts
packages/plugin-js-packages/src/lib/runner/index.ts
packages/plugin-js-packages/src/lib/runner/outdated/constants.ts
packages/plugin-js-packages/src/lib/runner/outdated/types.ts
packages/plugin-js-packages/src/lib/runner/outdated/unify-type.ts
packages/plugin-js-packages/src/lib/runner/outdated/unify-type.unit.test.ts

Related to #542 
In this PR, I add the support for Yarn v2. Notable changes:
- I updated the documentation regarding the Yarn v2 specific things.
- Yarn v2 does not support security audit for optional dependencies. This audit is skipped.
- I improved the plugin title.
Known issues:
- I was unable to find an indirect vulnerability so the logic is not verified.
The results were tested on jest repository.

feat(plugin-js-packages): add Yarn v2 support

---

.github/labeler.yml

E.g. PR #622 was assigned [📖 Project documentation](https://github.com/code-pushup/cli/labels/%F0%9F%93%96%20Project%20documentation) label, but the `.md` changes are all test snapshots.

ci: do not assign docs label if .md file changed in __snapshots__

---

packages/plugin-js-packages/src/lib/runner/outdated/transform.ts
packages/plugin-js-packages/src/lib/runner/outdated/transform.unit.test.ts

In this PR, I am temporarily skipping package labels and stick to comparing semantic versions.
Including the extended version description will be once `semver` is integrated in #597.
I documented current behaviour in unit tests.

fix(plugin-js-packages): skip package labels until semver is integrated

---

packages/plugin-js-packages/package.json
packages/plugin-js-packages/src/lib/runner/outdated/constants.ts
packages/plugin-js-packages/src/lib/runner/outdated/transform.ts
packages/plugin-js-packages/src/lib/runner/outdated/transform.unit.test.ts
packages/plugin-js-packages/src/lib/runner/outdated/types.ts

Related to #597 
In this PR, I use [`semver` functions](https://github.com/npm/node-semver?tab=readme-ov-file#functions) to determine the version difference.

refactor(plugin-js-packages): use semver for version diff

---

packages/plugin-js-packages/src/lib/package-managers/yarn-classic/constants.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-classic/outdated-result.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-classic/outdated-result.unit.test.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-classic/types.ts
packages/plugin-js-packages/src/lib/runner/outdated/types.ts

Related to #597 
The number of fields in Yarn v1 outdated result is dynamic. I now calculate the index of each relevant field, check all required fields are present and use their information to provide the audit outputs.
Note: Was tested on `rx-angular`. Should be tested on the previously failing project cc @matejchalk

fix(plugin-js-packages): consider dynamic outdated fields for Yarn v1

---

packages/plugin-js-packages/src/lib/runner/audit/transform.ts
packages/plugin-js-packages/src/lib/runner/audit/transform.unit.test.ts

Related to #597 
When unable to detect direct dependency name, the issue message omits it now.
Before it formatted the empty string.

fix(plugin-js-packages): omit unspecified direct dependency

---

code-pushup.config.ts
packages/plugin-eslint/README.md
packages/plugin-eslint/src/index.ts
packages/plugin-eslint/src/lib/nx.integration.test.ts
packages/plugin-eslint/src/lib/nx/find-all-projects.ts
packages/plugin-eslint/src/lib/nx/find-project-with-deps.ts
packages/plugin-eslint/src/lib/nx/find-project-without-deps.ts
packages/plugin-eslint/src/lib/nx/index.ts

fixes #675 
Desired helpers API after the changes:

feat(plugin-eslint): eslint config from nx projects helpers

---

.github/workflows/release.yml
packages/cli/docs/custom-plugins.md
packages/plugin-coverage/src/lib/runner/lcov/__snapshots__/lcov-runner.integration.test.ts.snap
packages/plugin-coverage/src/lib/runner/lcov/transform.ts
packages/plugin-coverage/src/lib/runner/lcov/transform.unit.test.ts
packages/plugin-js-packages/src/lib/runner/audit/transform.ts
packages/plugin-js-packages/src/lib/runner/audit/transform.unit.test.ts
packages/plugin-js-packages/src/lib/runner/outdated/transform.ts
packages/plugin-js-packages/src/lib/runner/outdated/transform.unit.test.ts
tools/scripts/start-local-registry.ts

- To differentiate audits which may produce issues but didn't find any from audits which never produce issues (useful for display purposes), made sure Code coverage and JS Packages always output `issues` array.
- Fixed (hopefully :crossed_fingers:) NPM publish in release workflow, `nx release` uses a different environment variable for the NPM access token (according to [docs](https://nx.dev/recipes/nx-release/publish-in-ci-cd#configure-the-nodeauthtoken)).

fix(plugin-coverage,plugin-js-packages): always include issues array, even if empty

---

packages/plugin-js-packages/README.md
packages/plugin-js-packages/src/lib/config.ts
packages/plugin-js-packages/src/lib/config.unit.test.ts
packages/plugin-js-packages/src/lib/constants.ts
packages/plugin-js-packages/src/lib/js-packages-plugin.ts
packages/plugin-js-packages/src/lib/js-packages-plugin.unit.test.ts
packages/plugin-js-packages/src/lib/package-managers/npm/npm.ts
packages/plugin-js-packages/src/lib/package-managers/pnpm/pnpm.ts
packages/plugin-js-packages/src/lib/package-managers/types.ts
packages/plugin-js-packages/src/lib/runner/index.ts
packages/plugin-js-packages/src/lib/runner/runner.integration.test.ts

In this PR, I make the following changes:
- dependency groups are configurable
- weights are adjusted to make optional dependencies have less influence on the score
As a side-effect, optional audits will no longer appear on portal for our current CLI config (can be changed).

refactor(plugin-js-packages): make optional deps opt-in, adjust weights

---

packages/plugin-eslint/README.md
packages/plugin-eslint/src/lib/nx.integration.test.ts
packages/plugin-eslint/src/lib/nx/projects-to-config.unit.test.ts
packages/plugin-eslint/src/lib/nx/utils.ts

Partially reverts #683. Omitting the config file produces [warnings](https://github.com/code-pushup/cli/actions/runs/9284755601/job/25547803390?pr=686#step:5:14438). I'm keeping the config file optional, but reverting back to explicit config in Nx helpers since it appears to be introducing more problems if otherwise :confused:

fix(plugin-eslint): revert to explicit config file in nx helper

---

packages/plugin-coverage/README.md
packages/plugin-coverage/src/lib/runner/lcov/lcov-runner.ts
packages/plugin-coverage/src/lib/runner/lcov/merge-lcov.ts
packages/plugin-coverage/src/lib/runner/lcov/merge-lcov.unit.test.ts

Closes #560 
Fixes part of #647 
In this PR, I implement a merging logic in order to collect coverage for the same file system from multiple test suites:
- In case different coverage runs identify different branches of code/functions, all that are identified by any tool are registered.
- The hits of functions, branches and lines are merged. As long as a function, branch or line is covered by at least one test suite, it is considered covered.
Tested on our CLI + unit tested.

fix(plugin-coverage): merge multiple results for a file

---

.github/labeler.yml
.github/workflows/release.yml

Possibly fixes Nx release in CI, at least partially :crossed_fingers:

ci: fix release step

---

e2e/cli-e2e/tests/__snapshots__/collect.e2e.test.ts.snap
packages/plugin-coverage/README.md
packages/plugin-coverage/src/lib/runner/constants.ts
packages/plugin-coverage/src/lib/runner/lcov/transform.ts
packages/plugin-coverage/src/lib/runner/lcov/transform.unit.test.ts

Closes #647 
In this PR, I skip missing coverage for functions called `(empty-report)`. They usually point to the first line of a file, an `import` or `export`. Therefore, this seems like an invalid function identification.

chore(plugin-coverage): skip missing coverage for empty-report function

---

packages/plugin-coverage/src/lib/nx/coverage-paths.ts
packages/plugin-coverage/src/lib/nx/coverage-paths.unit.test.ts
packages/plugin-coverage/src/lib/runner/lcov/lcov-runner.integration.test.ts
packages/plugin-coverage/src/lib/runner/lcov/lcov-runner.ts
packages/plugin-coverage/src/lib/runner/lcov/lcov-runner.unit.test.ts
packages/plugin-coverage/vite.config.unit.ts

Closes #536 
Related to https://github.com/code-pushup/cli/pull/604#discussion_r1555497103
In this PR, I make the following changes:
- The nx path helper should now correctly resolve Jest config as commonJS.
- The nx path helper should now only include the project path for Vitest where it is relative and not for Jest.
- I added a warning for empty LCOV files. Unfortunately, since logs from within plugins are not displayed unless the plugin crashes, this will only be visible after #695 
- I unit tested the nx helper and parsing LCOV files (object or string can be passed as a path).

chore(plugin-coverage): fix path helper for Jest, warn about empty lcov files

---

packages/plugin-js-packages/README.md
packages/plugin-js-packages/src/lib/config.ts
packages/plugin-js-packages/src/lib/config.unit.test.ts
packages/plugin-js-packages/src/lib/runner/index.ts
packages/plugin-js-packages/src/lib/runner/outdated/types.ts
packages/plugin-js-packages/src/lib/runner/runner.integration.test.ts
packages/plugin-js-packages/src/lib/runner/utils.ts
packages/plugin-js-packages/src/lib/runner/utils.unit.test.ts

Closes #666
In this PR, I implement the following changes:
- When `stderr` is not empty for `audit` or `outdated`, plugin throws and prints the `stderr`.
- `package.json` search is implemented: By default, only root `package.json` is used. An array of multiple `package.json` files may be explicitly provided. There is also an `autoSearch` option which merges all dependencies across all `package.json` files in the repository excluding cache and `node_modules`.
All package managers seem to have empty `stderr` for a successful audit. Not sure about deprecated behaviour.
- `npm` and `pnpm` successfully perform audit even when there are out-of-sync issues.
- `yarn-classic` throws an error for out of sync.
- `yarn-modern` reports errors into `stdout` (?!) when there are dependencies out of sync. …

chore(plugin-js-packages): stop plugin for non-empty stderr

---

code-pushup.config.ts
packages/plugin-lighthouse/src/lib/normalize-flags.unit.test.ts
packages/plugin-lighthouse/src/lib/runner/constants.ts
packages/plugin-lighthouse/src/lib/runner/runner.ts
packages/plugin-lighthouse/src/lib/runner/runner.unit.test.ts
packages/plugin-lighthouse/src/lib/runner/utils.ts
packages/plugin-lighthouse/src/lib/runner/utils.unit.test.ts

This PR is part of #695 
It includes:
- set and forward logLevel in `plugin-lighthouse` runner
- set lighthouse CLI flag `quiet` to `true` by default (hide logs by default)
- adopt and rename setLoglevel function
- extend unit-tests
- use new implementation to display logs in the CI

feat(plugin-lighthouse): add logLevel to lighthouse runner flags

---

packages/utils/src/lib/formatting.ts
packages/utils/src/lib/formatting.unit.test.ts

This PR extends the functionality for `truncateText` with:
- an additional overload for the options. before: `maxLength: number` after: `maxLength: number || {maxLength: number; position: string; ellipsis: string}`
- add ellipsis symbol at: `start` or `end` or `middle` 
- configure the ellipsis symbol

feat(utils): extend truncate text

---

e2e/cli-e2e/project.json
e2e/nx-plugin-e2e/project.json
examples/plugins/project.json
examples/react-todos-app/project.json
packages/cli/project.json
packages/core/project.json
packages/core/src/lib/implementation/read-rc-file.ts
packages/models/project.json
packages/nx-plugin/project.json
packages/plugin-coverage/package.json
packages/plugin-coverage/project.json
packages/plugin-coverage/src/lib/nx/coverage-paths.ts
packages/plugin-coverage/src/lib/nx/coverage-paths.unit.test.ts
packages/plugin-eslint/project.json
packages/plugin-js-packages/project.json
packages/plugin-lighthouse/project.json
packages/plugin-lighthouse/src/lib/runner/utils.ts
packages/utils/mocks/fixtures/valid-cjs-module-export.cjs
packages/utils/project.json
packages/utils/src/index.ts
packages/utils/src/lib/file-system.integration.test.ts
packages/utils/src/lib/file-system.ts
testing/test-utils/project.json

Fixes:
- #716
- #728 
- #727 
- #726 
All of these fixes are needed for integrating coverage plugin in portal.

fix(plugin-coverage): handle different Jest/Vitest config scenarios in Nx helper

---

e2e/cli-e2e/tests/__snapshots__/help.e2e.test.ts.snap
e2e/cli-e2e/tests/print-config.e2e.test.ts
packages/cli/src/lib/implementation/validate-plugin-filter-options.utils.ts

- Fixes [failing E2E tests](https://github.com/code-pushup/cli/actions/runs/9887801155/job/27310310532) after #730 was merged.
- Will look into how we can get GitHub Actions to trigger CI workflow for PRs from forks, and also skip Code PushUp upload ([fails due to missing secrets](https://github.com/code-pushup/cli/actions/runs/9830652625/job/27222815753)).

test(cli-e2e): fix E2E tests after --skipPlugins option added

---

.github/workflows/assign-pr-author.yml
.github/workflows/ci.yml
.github/workflows/code-pushup-fork.yml
.github/workflows/code-pushup.yml
code-pushup.config.ts

PR from forks weren't triggering our main CI workflow, and other workflows were broken. Attempted to fix these problems and tested what I could.
- CI workflow now runs on `pull_request` event also (forks don't run on `push`).
- Code PushUp workflow needs access to secrets, so it is now skipped for forks. 
- Create a separate Code PushUp workflow without secrets that should run only for forks. It won't upload anything, but the PR comments should still work. Can't test it before merging the workflow though, due to [how `pull_request_target` event works](https://github.com/orgs/community/discussions/54937#discussioncomment-5848312).
- Assigning PR author failed for my fork because of invalid permissions, should be solved by changing `pull_request` to `pull_request_target` (again, can't test …

ci: fix workflow triggers for forks

---

README.md
package.json

When we used `jscutlery/semver`, it used to bump the version in root `package.json`, but `nx release` doesn't do that. So I changed the source to [latest GitHub Release](https://github.com/code-pushup/cli/releases/latest).
- [before](https://github.com/code-pushup/cli/tree/7216f6eb689825f5e108fed4942510ae3ba8f368?tab=readme-ov-file#comprehensive-tech-quality-monitoring)
- [after](https://github.com/code-pushup/cli/tree/5fdeee0a898e71417bcebc6ee67dd4f022e5b3d1?tab=readme-ov-file#comprehensive-tech-quality-monitoring)

docs: fix outdated version badge in readme

---

packages/utils/src/index.ts
packages/utils/src/lib/merge-configs.ts
packages/utils/src/lib/merge-configs.unit.test.ts

Introducing a helper function to deep merge config objects.
Implemented:
Could be used in https://github.com/code-pushup/cli/pull/706 to support extraction & simplify configs

feat(utils): merge configs function

---

code-pushup.config.ts

The `verbose: true` in Lighthouse plugin spams all our `code-pushup` runs with over 17.5k logs ([example here](https://github.com/code-pushup/cli/actions/runs/9947211072/job/27479400492?pr=750#step:5:17590)) :scream:

ci(plugin-lighthouse): turn off verbose logging to make code-pushup output readable

---

packages/nx-plugin/src/executors/internal/cli.ts
packages/nx-plugin/src/executors/internal/cli.unit.test.ts
packages/utils/src/lib/transform.ts
packages/utils/src/lib/transform.unit.test.ts

Hotfix for #737 
**before:**
`parseObjToCliArgs({persist: {format: ['md', 'json']}})` => `--persist.format="md,json"`
**after:**
`parseObjToCliArgs({persist: {format: ['md', 'json']}})` => `--persist.format="md" --persist.format="json"`

feat(utils): add nested objects to cli args parsing

---

package-lock.json
package.json
packages/cli/src/lib/compare/compare-command.ts
packages/cli/src/lib/compare/compare-command.unit.test.ts
packages/core/package.json
packages/core/src/lib/compare.ts
packages/core/src/lib/compare.unit.test.ts
packages/utils/src/index.ts
packages/utils/src/lib/reports/__snapshots__/report-diff-with-portal-link.md
packages/utils/src/lib/reports/generate-md-reports-diff.integration.test.ts
packages/utils/src/lib/reports/generate-md-reports-diff.ts
packages/utils/src/lib/reports/load-report.ts
packages/utils/src/lib/reports/load-report.unit.test.ts
packages/utils/src/lib/reports/utils.ts
packages/utils/src/lib/reports/utils.unit.test.ts
testing/test-setup/src/lib/portal-client.mock.ts

Closes #681 
It works! :tada: https://github.com/code-pushup/cli/pull/760#issuecomment-2243357752

feat(cli,core,utils): include optional link to portal in markdown comment

---

code-pushup.config.ts
code-pushup.preset.ts
packages/utils/src/lib/merge-configs.unit.test.ts

This PR adds a `code-pushup.preset.ts` and uses the preset in `code-pushup.config.ts`
Notice: 
Coverage helper still unfinished.

refactor: add code-pushup.preset.ts

---

packages/plugin-js-packages/package.json
packages/plugin-js-packages/src/lib/runner/audit/transform.ts
packages/plugin-js-packages/src/lib/runner/audit/transform.unit.test.ts
packages/plugin-js-packages/src/lib/runner/outdated/transform.ts
packages/utils/src/index.ts
packages/utils/src/lib/reports/log-stdout-summary.unit.test.ts
packages/utils/src/lib/transform.ts
packages/utils/src/lib/transform.unit.test.ts

refactor(plugin-js-packages): use build-md to format issue messages

---

esbuild.config.js
package.json
packages/cli/package.json
packages/core/package.json
packages/models/package.json
packages/nx-plugin/package.json
packages/plugin-coverage/package.json
packages/plugin-eslint/package.json
packages/plugin-js-packages/package.json
packages/plugin-lighthouse/package.json
packages/utils/package.json

Updated:
- description
- homepage
Removed:
- contributors (better maintained by github)
Added:
- packageManager for us devs in root `package.json`
closes 
#632

docs: update package.json docs

---

packages/plugin-lighthouse/src/lib/runner/details/details.unit.test.ts
packages/plugin-lighthouse/src/lib/runner/details/table.type.ts
packages/plugin-lighthouse/src/lib/runner/details/table.type.unit.test.ts
packages/plugin-lighthouse/src/lib/runner/utils.unit.test.ts

feat(plugin-lighthouse): omit audit details table title

---

packages/utils/src/lib/reports/__snapshots__/report-diff-added.md
packages/utils/src/lib/reports/__snapshots__/report-diff-improved.md
packages/utils/src/lib/reports/__snapshots__/report-diff-mixed.md
packages/utils/src/lib/reports/__snapshots__/report-diff-unchanged.md
packages/utils/src/lib/reports/__snapshots__/report-diff-with-portal-link.md
packages/utils/src/lib/reports/__snapshots__/report-stdout-no-categories.txt
packages/utils/src/lib/reports/__snapshots__/report-stdout.txt
packages/utils/src/lib/reports/__snapshots__/report.md
packages/utils/src/lib/reports/log-stdout-summary.ts
testing/test-utils/src/lib/utils/dynamic-mocks/lighthouse-audits.mock.ts

Closes #665 
<details>
<summary>Screenshots</summary>
<p></p>
<p>Before:</p>
<p></p>
<p>After:</p>
<p></p>
<p>Before:</p>
<p></p>
<p>After:</p>
</details>

feat(utils): increase audit value column width

---

packages/plugin-lighthouse/src/lib/runner/utils.ts
packages/plugin-lighthouse/src/lib/runner/utils.unit.test.ts
packages/utils/src/index.ts

refactor(plugin-lighthouse): format audit value

---

packages/plugin-lighthouse/src/lib/lighthouse-plugin.ts
packages/plugin-lighthouse/src/lib/normalize-flags.ts
packages/plugin-lighthouse/src/lib/normalize-flags.unit.test.ts
packages/plugin-lighthouse/src/lib/runner/utils.ts

Closes #612 
This PR addresses an issue where the `skipAudits` flag was being ignored if `onlyAudits` or `onlyCategories` were present as empty arrays in the Lighthouse plugin configuration. The `normalizeFlags` function has been updated to remove any flags with empty array values, ensuring that `skipAudits` operates correctly.
In Lighthouse, the `onlyAudits`, `onlyCategories`, and `skipAudits` flags are used to determine which audits to include in the report. However, a bug occurred when `onlyAudits` or `onlyCategories` were provided as empty arrays. This caused the `skipAudits` flag to be ignored, leading to all audits being included in the report, even those that were supposed to be skipped.
Source: [https://github.com/GoogleChrome/lighthouse/blob/main/core/config/filters.js#L269-L276]( …

fix(plugin-lighthouse): process empty array flags

---

e2e/cli-e2e/tests/__snapshots__/help.e2e.test.ts.snap
packages/cli/README.md
packages/cli/src/lib/commands.ts
packages/cli/src/lib/compare/compare-command.ts
packages/cli/src/lib/compare/compare-command.unit.test.ts
packages/cli/src/lib/implementation/compare.model.ts
packages/cli/src/lib/implementation/compare.options.ts
packages/cli/src/lib/implementation/merge-diffs.model.ts
packages/cli/src/lib/implementation/merge-diffs.options.ts
packages/cli/src/lib/merge-diffs/merge-diffs-command.ts
packages/cli/src/lib/merge-diffs/merge-diffs-command.unit.test.ts
packages/cli/src/lib/yargs-cli.integration.test.ts
packages/core/src/index.ts
packages/core/src/lib/compare.ts
packages/core/src/lib/compare.unit.test.ts
packages/core/src/lib/merge-diffs.ts
packages/core/src/lib/merge-diffs.unit.test.ts
packages/models/docs/models-reference.md
packages/models/src/lib/reports-diff.ts
packages/models/src/lib/reports-diff.unit.test.ts
packages/utils/src/index.ts
packages/utils/src/lib/errors.ts
packages/utils/src/lib/errors.unit.test.ts
packages/utils/src/lib/reports/generate-md-reports-diff.integration.test.ts
packages/utils/src/lib/reports/generate-md-reports-diff.ts

Part of #731 (CLI)
New `merge-diffs` command implemented, which parses list of `report-diff.json` paths from required `--files` option and uses Markdown formatter from #793 to generate single `report-diff.md`.
Also added a `--label` option to `compare` command, which can be used to set project names for the JSON diffs (parent directory used as fallback).

feat(cli): implement `merge-diffs` command

---

packages/utils/src/lib/reports/__snapshots__/report.md
packages/utils/src/lib/reports/__snapshots__/sorting.integration.test.ts.snap
packages/utils/src/lib/reports/sorting.unit.test.ts
packages/utils/src/lib/reports/utils.ts
packages/utils/src/lib/reports/utils.unit.test.ts

Closes #571 
This PR updates the order of checks from `weight > score > value > title` to `score > weight > value > title` to prioritize sorting by score. This change ensures that failed audits appear before passed ones in the report.

refactor(utils): prioritize score in sort order

---

.github/workflows/ci.yml

Fixes unintended consequence from:
- #743
The CI is triggered on `push` _and_ on `pull_request` (was only `on: push` before, but that didn't work for forks). This means that the workflow and all its jobs _run twice_ on every push to an open PR, or when pushing to branch and then opening a new PR. 
Simplest solution was to restrict `push` trigger to `main` branch. This means CI won't be triggered by push to any branch anymore, there needs to be an open PR (can be a draft).

ci: prevent duplicate CI runs when pushing to open PR

---

packages/utils/src/lib/formatting.unit.test.ts
packages/utils/src/lib/reports/utils.unit.test.ts
packages/utils/src/lib/transform.unit.test.ts

Closes #272 
> [!NOTE]  
> - `formatDuration` already had some coverage. It was slightly extended
> - `getSeverityIcon` mentioned in the issue doesn't exist anymore 
> - `tableHtml` has been renamed to `table` and tested since the issue was created
> - `loadReport` has also been tested

test(utils): extend unit tests

---

packages/cli/src/lib/implementation/validate-plugin-filter-options.utils.ts
packages/cli/src/lib/implementation/validate-plugin-filter-options.utils.unit.test.ts

Fixes #565 
- Ensure warnings for invalid plugin filter options are logged regardless of the `--verbose` flag.
- Improve message clarity by handling both singular and plural cases.
- Update unit tests to reflect changes in logging behavior and message wording.

refactor(cli): improve plugin filter option validation

---

e2e/cli-e2e/tests/__snapshots__/help.e2e.test.ts.snap
packages/cli/src/lib/implementation/only-plugins.options.ts
packages/cli/src/lib/implementation/skip-plugins.options.ts

Closes #672 
This PR adds aliases for `--onlyPlugins` and `--skipPlugins`.

feat(cli): add command option aliases

---

packages/utils/src/lib/reports/__snapshots__/report-diff-changed.md
packages/utils/src/lib/reports/__snapshots__/report-diff-monorepo-changed.md
packages/utils/src/lib/reports/generate-md-reports-diff.integration.test.ts
packages/utils/src/lib/reports/generate-md-reports-diff.ts
testing/test-utils/src/lib/utils/dynamic-mocks/report-diff.mock.ts

This PR resolves an issue with the report formatting logic where changes that did not affect the score were not being handled correctly. Specifically, it ensures that a categories table is excluded from the monorepo report when none of the category scores have been affected.
Closes #819

fix(utils): format reports with unchanged score

---

packages/cli/src/lib/implementation/filter-plugins.middleware.ts
packages/cli/src/lib/implementation/filter-plugins.middleware.unit.test.ts
packages/cli/src/lib/implementation/global.utils.ts
packages/cli/src/lib/implementation/global.utils.unit.test.ts
packages/cli/src/lib/implementation/validate-plugin-filter-options.utils.ts
packages/cli/src/lib/implementation/validate-plugin-filter-options.utils.unit.test.ts

Closes #823 
This PR improves error handling for `--onlyPlugins` and `--skipPlugins`, ensuring the command aborts when no valid plugins are provided to `--onlyPlugins`. Invalid plugins are ignored with warnings, and conflicts between the two options are handled with clear error messages.

feat(cli): handle invalid plugin filter options

---

code-pushup.preset.ts
e2e/plugin-lighthouse-e2e/mocks/fixtures/code-pushup.config.lh-default.ts
packages/plugin-lighthouse/README.md
packages/plugin-lighthouse/package.json
packages/plugin-lighthouse/src/index.ts
packages/plugin-lighthouse/src/lib/constants.ts
packages/plugin-lighthouse/src/lib/normalize-flags.unit.test.ts
packages/plugin-lighthouse/src/lib/runner/constants.ts

Closes #764 
This pull request introduces `DEFAULT_CHROME_FLAGS` to `@code-pushup/lighthouse-plugin`, combining Chrome's default flags provided by `chrome-launcher` with `--headless` for streamlined headless execution. 
The README has been updated to reflect this change.

feat(plugin-lighthouse): export default Chrome flags

---

packages/core/src/lib/collect-and-persist.ts
packages/core/src/lib/collect-and-persist.unit.test.ts
packages/core/src/lib/implementation/persist.ts
packages/core/src/lib/implementation/persist.unit.test.ts
packages/utils/src/lib/reports/__snapshots__/report-stdout-all-perfect-scores.txt
packages/utils/src/lib/reports/__snapshots__/report-stdout-no-categories.txt
packages/utils/src/lib/reports/__snapshots__/report-stdout-verbose.txt
packages/utils/src/lib/reports/log-stdout-summary.integration.test.ts
packages/utils/src/lib/reports/log-stdout-summary.ts
packages/utils/src/lib/reports/log-stdout-summary.unit.test.ts

Closes #830 
This pull request focuses on improving the terminal output by skipping audits with perfect scores and refactoring the code.
- `verbose` option is now passed to `logStdoutSummary`
- stdout logging is moved from `persistReport` to `collectAndPersistReports`
- `logPlugins` is refactored to skip audits with perfect scores
- test coverage is added

feat: skip perfect scores in stdout summary

---

.github/workflows/ci.yml

The code pushup js check NPM audit packages plugin now

build: remove npm audit from CI

---

e2e/plugin-lighthouse-e2e/tests/collect.e2e.test.ts
packages/cli/README.md
packages/cli/src/lib/autorun/autorun-command.ts
packages/cli/src/lib/upload/upload-command.ts
packages/core/package.json
packages/core/src/lib/compare.ts
packages/core/src/lib/load-portal-client.ts
packages/core/src/lib/upload.ts

Closes #474 
- Make `@code-pushup/portal-client` an optional peer dependency in the `@code-pushup/core` package.
- Update the core package to use dynamic imports for `@code-pushup/portal-client`.
- Add a utility function to handle the loading of the portal client.
- Update the installation instructions to guide users on omitting optional dependencies, including details for `npm`, `pnpm`, and `yarn` setups.

feat: make portal-client dependency optional

---

.github/labeler.yml
packages/ci/src/index.ts
packages/ci/src/lib/monorepo/index.ts
packages/ci/src/lib/monorepo/tools.ts

Integrating `ci` package in GitHub Action as part of #829, realized a few more exports would be useful for types and runtime validation.

feat(ci): add useful exports

---

packages/core/src/lib/implementation/report-to-gql.ts

Related:
- #474 
- #837 
Ran into error when `@code-pushup/cli` installed without `@code-pushup/portal-client`. There was a leftover static non-type import for converting CLI reports to portal. Came up with a type-safe way to not have to use the enum objects.

fix(core): avoid portal-client import for enum conversions

---

esbuild.config.js
package.json
packages/ci/package.json
packages/cli/docs/custom-plugins.md
packages/cli/package.json
packages/core/package.json
packages/create-cli/package.json
packages/models/package.json
packages/nx-plugin/package.json
packages/plugin-coverage/package.json
packages/plugin-eslint/package.json
packages/plugin-js-packages/package.json
packages/plugin-lighthouse/package.json
packages/utils/package.json

closes #848 
- NPM displays keywords and uses them for search categorizing, I've added a few so our package is more visible

refactor: move metadata into each of the sub-package `package.json` and add keywords

---

packages/models/src/lib/implementation/utils.ts
packages/plugin-coverage/src/lib/runner/lcov/utils.ts
packages/plugin-eslint/src/lib/meta/groups.ts
packages/plugin-eslint/src/lib/runner/transform.ts
packages/utils/src/lib/reports/generate-md-reports-diff-utils.ts
packages/utils/src/lib/reports/generate-md-reports-diff-utils.unit.test.ts
packages/utils/src/lib/reports/sorting.ts
packages/utils/src/lib/reports/utils.unit.test.ts
packages/utils/src/lib/text-formats/table.ts

refactor: use `toSorted` in appropriate places

---

packages/ci/src/lib/run.ts

Came across error in monorepo mode when triggered on `push` and not `pull_request`. Falls through to standalone mode.

fix(ci): handle monorepo mode in non-PR flow

---

packages/plugin-eslint/README.md
packages/plugin-eslint/src/lib/nx.integration.test.ts
packages/plugin-eslint/src/lib/nx/filter-project-graph.ts
packages/plugin-eslint/src/lib/nx/filter-project-graph.unit.test.ts
packages/plugin-eslint/src/lib/nx/find-all-projects.ts
packages/plugin-eslint/src/lib/nx/projects-to-config.unit.test.ts
testing/test-utils/src/index.ts
testing/test-utils/src/lib/utils/project-graph.ts

Closes #496 
This PR adds an exclude option to the `eslintConfigFromAllNxProjects` function, allowing Nx projects to be selectively excluded from ESLint configuration and additionally moves the `toProjectGraph` helper into `test-utils` for reuse across test suites.

feat(plugin-eslint): add exclude option for Nx projects

---

packages/plugin-coverage/package.json
packages/plugin-eslint/package.json

Not possible to install these plugins without `--legacy-peer-deps` otherwise for Nx 20.

fix(plugin-eslint,plugin-coverage): future-proof version range of nx peer deps

---

packages/models/src/lib/reports-diff.ts

fix(models): allow non-integers in audit values diff

---

packages/ci/README.md
packages/ci/src/lib/models.ts
packages/ci/src/lib/run.integration.test.ts
packages/ci/src/lib/run.ts

Artifact cache wasn't working correctly in monorepo mode. This change will allow provider integrations to download the correct report based on the project name. Also improved error handling and docs.

fix(ci): pass project name to downloadReportArtifact and ignore errors

---

packages/plugin-js-packages/README.md

`plugin` and `slug` were inverted.
Check this [poetic discussion](https://push-based.slack.com/archives/C06JCR9L1FE/p1732813464191089?thread_ts=1732809995.748769&cid=C06JCR9L1FE) for a reference.

docs: update plugin-js-packages example

---

packages/ci/README.md
packages/ci/src/lib/constants.ts
packages/ci/src/lib/models.ts
packages/ci/src/lib/monorepo/handlers/nx.ts
packages/ci/src/lib/monorepo/list-projects.ts
packages/ci/src/lib/monorepo/list-projects.unit.test.ts
packages/ci/src/lib/monorepo/tools.ts

Request from Nx customer where they need some custom projects filters. Forwarding args to [`nx show projects`](https://nx.dev/nx-api/nx/documents/show#projects) gives the most flexibility. Option is Nx specific because other monorepo tools are based on `package.json`s, so don't have a CLI for listing projects.

feat(ci): add nxProjectsFilter option, forwards custom filters to Nx CLI

---

package-lock.json
package.json
packages/core/package.json
packages/core/src/lib/implementation/read-rc-file.integration.test.ts
packages/core/src/lib/implementation/read-rc-file.ts
packages/models/src/lib/category-config.ts
packages/models/src/lib/category-config.unit.test.ts
packages/models/src/lib/group.ts
packages/models/src/lib/group.unit.test.ts
packages/models/src/lib/implementation/schemas.ts
packages/plugin-lighthouse/src/lib/lighthouse-plugin.unit.test.ts
packages/utils/package.json
packages/utils/src/index.ts
packages/utils/src/lib/zod-validation.ts
packages/utils/src/lib/zod-validation.unit.test.ts

Fixes #704 
This PR introduces `zod-validation-error` as a new project dependency to make `Zod` validation errors more compact and readable. Due to the limited scope of the issue being resolved, `zod-validation-error` is currently used only to validate `coreConfigSchema`.
<details>
<summary>Formatted config validation errors</summary>
</details>

feat(core): enhance config validation

---

eslint.config.js
packages/plugin-coverage/src/lib/runner/runner.integration.test.ts
packages/plugin-js-packages/src/lib/js-packages-plugin.ts
packages/plugin-js-packages/src/lib/runner/runner.integration.test.ts
packages/plugin-lighthouse/src/lib/normalize-flags.ts
packages/plugin-lighthouse/src/lib/utils.ts
packages/utils/src/lib/zod-validation.unit.test.ts

Now that we build using `tsc` for ESM runtime, imports without `.js` extensions have to be linted to prevent runtime errors.

fix: lint import extensions and fix missing .js extensions

---

packages/plugin-eslint/src/lib/meta/parse.ts
packages/plugin-eslint/src/lib/meta/parse.unit.test.ts

Some rules from `eslint-plugin-n` weren't being discovered correctly, was being [logged as warning](https://github.com/code-pushup/cli/actions/runs/12370364730/job/34524165627#step:5:25):
This is because for rule IDs like `n/prefer-promises/fs` the parser incorrectly identified which part was the plugin name.
Now that the parsing was adjusted, the [warnings are gone](https://github.com/code-pushup/cli/actions/runs/12372744687/job/34531635769?pr=895#step:5:25).

fix(plugin-eslint): parse rule names containing slashes correctly

---

testing/test-utils/src/lib/utils/git.ts

I've recently added a GPG signature to my commits and that broke running the integration tests locally for me 😅 this is fixing it

test(test-utils): disable GPG sign for commit/tag utility

---

packages/cli/src/lib/implementation/filter.middleware.ts
packages/cli/src/lib/implementation/filter.middleware.unit.test.ts
packages/cli/src/lib/implementation/filter.middleware.utils.ts
packages/cli/src/lib/implementation/filter.middleware.utils.unit.test.ts
packages/cli/src/lib/implementation/validate-filter-options.utils.ts
packages/cli/src/lib/implementation/validate-filter-options.utils.unit.test.ts
packages/models/docs/models-reference.md
packages/models/src/lib/audit.ts
packages/models/src/lib/core-config.unit.test.ts
packages/models/src/lib/group.ts
packages/models/src/lib/implementation/schemas.ts
packages/plugin-lighthouse/src/lib/lighthouse-plugin.ts
packages/plugin-lighthouse/src/lib/lighthouse-plugin.unit.test.ts
packages/plugin-lighthouse/src/lib/utils.ts
packages/plugin-lighthouse/src/lib/utils.unit.test.ts

Fixes #903 
This fix enhances the filtering of report results by audits and groups through the core configuration (currently implemented for the Lighthouse plugin only).
The `isSkipped` property is introduced in the `PluginConfig` metadata for audits and groups, ensuring the complete set of plugin audits and groups is retained during `CoreConfig` validation to prevent unexpected errors. Filtering is now deferred to the filter middleware, which accurately handles skipped items by removing categories that contain only skipped or zero-weight references.

fix: handle skipped audits and groups

---

packages/models/src/index.ts

Adds missing expected exports of `fileNameSchema` and `filePathSchema` of the package `models`

fix(models): add missing exports

---

packages/plugin-coverage/src/lib/nx/coverage-paths.ts

Vitest has an option to generate only lcov files without the HTML UI polluting the coverage folders.

feat(plugin-coverage): support lcovonly option for vitest

---

packages/core/package.json
packages/core/src/lib/implementation/read-rc-file.integration.test.ts
packages/core/src/lib/implementation/read-rc-file.ts
packages/plugin-eslint/README.md
packages/plugin-eslint/src/lib/config.ts
packages/plugin-eslint/src/lib/eslint-plugin.integration.test.ts
packages/plugin-eslint/src/lib/eslint-plugin.ts
packages/plugin-eslint/src/lib/meta/groups.ts
packages/plugin-eslint/src/lib/meta/groups.unit.test.ts
packages/plugin-eslint/src/lib/meta/index.ts
packages/plugin-eslint/src/lib/meta/rules.ts
packages/plugin-eslint/src/lib/meta/rules.unit.test.ts
packages/plugin-eslint/tsconfig.test.json
packages/plugin-eslint/vite.config.unit.ts
packages/utils/package.json
packages/utils/src/index.ts
packages/utils/src/lib/zod-validation.ts

Closes #897 
This PR introduces support for custom groups in the ESLint plugin, enabling users to define and categorize ESLint rules with custom weights and configurations.

feat(plugin-eslint): add support for custom groups

---

packages/core/src/lib/implementation/persist.unit.test.ts
packages/core/vite.config.unit.ts
packages/utils/src/lib/reports/generate-md-report.unit.test.ts
packages/utils/vite.config.unit.ts
testing/test-setup/src/lib/extend/markdown-table.matcher.ts
testing/test-setup/src/lib/extend/markdown-table.matcher.unit.test.ts
testing/test-setup/src/vitest.d.ts
testing/test-setup/vite.config.unit.ts

Closes #757 
This PR introduces a custom matcher, `toContainMarkdownTableRow`, designed to validate the presence of specific rows within Markdown tables during testing.

test: add custom matcher for markdown table rows

---

e2e/nx-plugin-e2e/tests/executor-cli.e2e.test.ts
packages/nx-plugin/README.md
packages/nx-plugin/src/executors/cli/README.md
packages/nx-plugin/src/executors/cli/executor.ts
packages/nx-plugin/src/executors/cli/utils.ts
packages/nx-plugin/src/executors/cli/utils.unit.test.ts
packages/nx-plugin/src/index.ts

Closes #753 
This PR implements deep merge for executor options, allowing CLI arguments to augment rather than override nested configurations.

fix(nx-plugin): deep merge executor options

---

packages/plugin-typescript/eslint.config.js
packages/plugin-typescript/package.json
packages/plugin-typescript/project.json
packages/plugin-typescript/src/index.ts
packages/plugin-typescript/src/lib/constants.ts
packages/plugin-typescript/tsconfig.json
packages/plugin-typescript/tsconfig.lib.json
packages/plugin-typescript/tsconfig.test.json
packages/plugin-typescript/vite.config.integration.ts
packages/plugin-typescript/vite.config.unit.ts
tsconfig.base.json

This PR include the foundation for the TypeScript plugin.
It includes Nx related files, testing and typescript setup.

feat(plugin-typescript): setup plugin project base

---

packages/cli/src/index.ts

CLI hangs in certain situations, we do open many sub processes and some of them maybe don't exit properly.
For immediate fix we need to explicitly exist with successful code.
closes #468

fix: explicitly exit process with successful code to not leave cli hanging

---

packages/plugin-coverage/src/lib/config.ts
packages/plugin-coverage/src/lib/runner/index.ts
packages/plugin-coverage/src/lib/runner/lcov/lcov-runner.ts
packages/plugin-coverage/src/lib/runner/lcov/lcov-runner.unit.test.ts

feat(plugin-coverage): do not halt plugin execution on fail

---

packages/ci/README.md
packages/ci/src/lib/constants.ts
packages/ci/src/lib/models.ts
packages/ci/src/lib/run-monorepo.ts
packages/ci/src/lib/run-standalone.ts
packages/ci/src/lib/run-utils.ts
packages/ci/src/lib/run.integration.test.ts

- Runs `git checkout -f ${refs.head.ref}` in case set to other than current HEAD. This is a preparation for new custom source ref GitLab input.
- New `skipComment` option added (`false` by default), so that PR/MR comment can be turned off easily. Will follow-up with exposing this as input for GitLab and GitHub.

feat(ci): add skipComment option, ensure head ref is checked out

---

e2e/plugin-jsdocs-e2e/tests/__snapshots__/report.txt
e2e/plugin-jsdocs-e2e/tests/collect.e2e.test.ts
packages/ci/src/lib/run-utils.ts

- Fixes Git error introduced in #938, discovered when [testing new version in GitLab pipelines](https://gitlab.com/code-pushup/gitlab-pipelines-template/-/jobs/9168638774#L60).
- Also fixes [flaky E2E test assertion in JSDocs plugin](https://github.com/code-pushup/cli/actions/runs/13388341977/job/37390107342?pr=939#step:6:700).

fix(ci): prevent ambigious ref when checking head

---

packages/cli/src/index.ts
packages/cli/src/lib/polyfills.ts

The runner with `use: 'node20'` in our GitHub action does not respect the Node 20 requirement and runs on Node 18 anyway, GitHub did not release a Node 22 runner for quite some time now and they do not communicate their plans at all, thus only reasonable thing we can do right now it to include a polyfill as execution of our code in action runner does not work and fails with no error in CI

fix: add `toSorted` polyfill as hotfix for bug in GitHub actions runner

---

packages/ci/src/lib/run-utils.ts

The [`git checkout` command errors for custom target refs](https://gitlab.com/code-pushup/gitlab-pipelines-template/-/jobs/9170064748#L110) (shallow fetch) specified by branch/tag name, so the commit SHA must be used.

fix(ci): prevent unknown pathspec error for custom base ref

---

packages/models/src/lib/audit.unit.test.ts
packages/models/src/lib/implementation/schemas.ts
packages/models/src/lib/implementation/schemas.unit.test.ts

The [`@nx/eslint:workspace-rule` generator](https://nx.dev/nx-api/eslint/generators/workspace-rule) uses `__filename` as `meta.docs.url` by default. This causes a validation error for the plugin config's `audit.docsUrl`, as a file path doesn't pass our `z.string().url()` validation. 
To reduce friction for users, the validation has been tweaked to tolerate invalid URLs. A warning is logged, and the invalid URL is removed from the metadata to prevent broken links.
Implemented using Zod's [`.catch()`](https://zod.dev/?id=catch) method.

feat(models): do not throw if docs url invalid, treat as missing and log warning

---

e2e/ci-e2e/tests/__snapshots__/basic-report-diff.md
e2e/ci-e2e/tests/__snapshots__/npm-workspaces-report-diff.md
e2e/ci-e2e/tests/__snapshots__/nx-monorepo-report-diff.md
e2e/cli-e2e/tests/__snapshots__/compare.report-diff.md
packages/utils/src/lib/reports/__snapshots__/report-diff-added.md
packages/utils/src/lib/reports/__snapshots__/report-diff-changed.md
packages/utils/src/lib/reports/__snapshots__/report-diff-improved.md
packages/utils/src/lib/reports/__snapshots__/report-diff-many-audits.md
packages/utils/src/lib/reports/__snapshots__/report-diff-minimal.md
packages/utils/src/lib/reports/__snapshots__/report-diff-mixed.md
packages/utils/src/lib/reports/__snapshots__/report-diff-monorepo-changed.md
packages/utils/src/lib/reports/__snapshots__/report-diff-monorepo-unchanged.md
packages/utils/src/lib/reports/__snapshots__/report-diff-monorepo-with-portal.md
packages/utils/src/lib/reports/__snapshots__/report-diff-monorepo.md
packages/utils/src/lib/reports/__snapshots__/report-diff-unchanged.md
packages/utils/src/lib/reports/__snapshots__/report-diff-with-portal.md
packages/utils/src/lib/reports/generate-md-reports-diff-utils.ts

The _source_ and _target_ terminology was the wrong way around :man_facepalming: Replaced with _current_ and _previous_, which is clearer.

fix(utils): replace misleading commit labels in markdown diff

---

e2e/cli-e2e/tests/print-config.e2e.test.ts
packages/ci/src/lib/cli/commands/print-config.ts
packages/ci/src/lib/run-monorepo.ts
packages/ci/src/lib/run-utils.ts
packages/ci/src/lib/run.integration.test.ts
packages/cli/README.md
packages/cli/src/lib/commands.ts
packages/cli/src/lib/implementation/print-config.model.ts
packages/cli/src/lib/implementation/print-config.options.ts
packages/cli/src/lib/print-config/print-config-command.ts
packages/cli/src/lib/print-config/print-config-command.unit.test.ts
packages/utils/src/index.ts
packages/utils/src/lib/random.ts
packages/utils/src/lib/random.unit.test.ts

Fixes #947 
Needs to updated in [GitHub Action](https://github.com/code-pushup/github-action) and [GitLab pipelines template](https://gitlab.com/code-pushup/gitlab-pipelines-template) after release.

feat(ci,cli): use new --output=<file> option for print-config instead of stdout

---

packages/ci/README.md
packages/ci/src/lib/git.ts
packages/ci/src/lib/models.ts
packages/ci/src/lib/run-monorepo.ts
packages/ci/src/lib/run-standalone.ts
packages/ci/src/lib/run-utils.ts
packages/ci/src/lib/run.ts
packages/utils/src/index.ts
packages/utils/src/lib/transform.ts
packages/utils/src/lib/transform.unit.test.ts

Should unblock GitHub Action release (currently [fails](https://github.com/code-pushup/github-action/actions/runs/13545884942/job/37857864118#step:5:51) in https://github.com/code-pushup/github-action/pull/145).

feat(ci): allow refs without shas, fetch if needed

---

packages/plugin-eslint/src/lib/runner.integration.test.ts
packages/utils/src/lib/execute-process.ts
packages/utils/src/lib/format-command-log.integration.test.ts
packages/utils/src/lib/format-command-log.ts

refactor(utils): make execute process log compact

---

e2e/ci-e2e/vite.config.e2e.ts
e2e/cli-e2e/vite.config.e2e.ts
e2e/create-cli-e2e/vite.config.e2e.ts
e2e/nx-plugin-e2e/vite.config.e2e.ts
e2e/plugin-coverage-e2e/vite.config.e2e.ts
e2e/plugin-eslint-e2e/vite.config.e2e.ts
e2e/plugin-jsdocs-e2e/vite.config.e2e.ts
e2e/plugin-lighthouse-e2e/vite.config.e2e.ts

test: adjust test timeouts

---

e2e/ci-e2e/tests/basic.e2e.test.ts
e2e/ci-e2e/tests/npm-workspaces.e2e.test.ts
e2e/ci-e2e/tests/nx-monorepo.e2e.test.ts
packages/ci/README.md
packages/ci/src/lib/models.ts
packages/ci/src/lib/output-files.ts
packages/ci/src/lib/output-files.unit.test.ts
packages/ci/src/lib/run-monorepo.ts
packages/ci/src/lib/run-standalone.ts
packages/ci/src/lib/run-utils.ts
packages/ci/src/lib/run.integration.test.ts

Fixes #946 
All output files are now immediately copied to a special `.code-pushup/.ci` folder, to prevent command outputs conflicting with artifact files.
```sh
.code-pushup/
├─ .ci/
│  ├─ .current/
│  │  ├─ report.json
│  │  ├─ report.md
```
```sh
.code-pushup/
├─ .ci/
│  ├─ .comparison/
│  │  ├─ report-diff.json
│  │  ├─ report-diff.md
│  ├─ .current/
│  │  ├─ report.json
│  │  ├─ report.md
│  ├─ .previous/
│  │  ├─ report.json
│  │  ├─ report.md # if cache not used
```
```sh
.code-pushup/
├─ .ci/
│  ├─ <project-name>/
│  │  ├─ .current/
│  │  │  ├─ report.json
│  │  │  ├─ report.md
│  ├─ # ... other projects ...
```
```sh
.code-pushup/
├─ .ci/
│  ├─ <project-name>/
│  │  ├─ .comparison/
│  │  │  ├─ report-diff.json
│  │  │  ├─ report-diff.md
│  │  ├─ .current/
│  │  │  ├─ report.json …
```

fix(ci): prevent overwriting report artifacts

---

packages/plugin-js-packages/src/lib/package-managers/yarn-classic/outdated-result.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-classic/types.ts

Fixes error in for Yarn v1 repo where there are no outdated packages, so `yarn oudated --json` doesn't print any JSON lines.
```
[ warn ] Plugins failed: 
[ warn ] Error: - Plugin JS Packages (js-packages) produced the following error:
- file:///REDACTED/node_modules/@code-pushup/js-packages-plugin/src/lib/package-managers/yarn-classic/outdated-result.js:6
const fields = yarnv1Outdated[1].data.head;
^
TypeError: Cannot read properties of undefined (reading 'data')
at Object.yarnv1ToOutdatedResult [as unifyResult] (file:///REDACTED/node_modules/@code-pushup/js-packages-plugin/src/lib/package-managers/yarn-classic/outdated-result.js:6:38)
at processOutdated (file:///REDACTED/node_modules/@code-pushup/js-packages-plugin/src/lib/runner/index.js:47:42)
at async executeRunner …
```

fix(plugin-js-packages): handle empty output from yarn outdated

---

nx.json

This PR should fix the error present locally & in CI, that has been caused by parallel `nxv-pkg-install` rewriting the `package.json` when installing dependencies in the per e2e `tmp` folder.
The error was recognizable in the logs as: 
`Cannot find package '@code-pushup/plugin-****' imported from ... code-pushup.config.bundled_****` 
This was happening randomly, only if the "plugin" was not installed last as it did not rewrite any of the important deps (cli, core,...), but if if was installed sooner, the specific package (cli, core, ...) would emit `package.json` without the plugin or any other important dependency.
<details><summary>Detailed examples of failing PRs</summary>
<p>
[Example from recent PR](https://github.com/code-pushup/cli/actions/runs/14183589314/job/39734694752?pr=898) …

test: disable parallel install of packages in e2e test

---

.verdaccio/config.yml
e2e/plugin-js-packages-e2e/eslint.config.js
e2e/plugin-js-packages-e2e/mocks/fixtures/npm-repo/code-pushup.config.ts
e2e/plugin-js-packages-e2e/mocks/fixtures/npm-repo/package-lock.json
e2e/plugin-js-packages-e2e/mocks/fixtures/npm-repo/package.json
e2e/plugin-js-packages-e2e/project.json
e2e/plugin-js-packages-e2e/tests/plugin-js-packages.e2e.test.ts
e2e/plugin-js-packages-e2e/tsconfig.json
e2e/plugin-js-packages-e2e/tsconfig.test.json
e2e/plugin-js-packages-e2e/vite.config.e2e.ts
packages/plugin-js-packages/README.md
packages/plugin-js-packages/src/lib/config.ts
packages/plugin-js-packages/src/lib/config.unit.test.ts
packages/plugin-js-packages/src/lib/package-managers/npm/outdated-result.ts
packages/plugin-js-packages/src/lib/package-managers/npm/outdated-result.unit.test.ts
packages/plugin-js-packages/src/lib/package-managers/npm/types.ts
packages/plugin-js-packages/src/lib/runner/index.ts
packages/plugin-js-packages/src/lib/runner/runner.integration.test.ts
packages/plugin-js-packages/src/lib/runner/utils.ts
packages/plugin-js-packages/src/lib/runner/utils.unit.test.ts

refactor(plugin-js-packages): provide package json path + e2e test

---

packages/utils/src/lib/git/git.commits-and-tags.ts

This error:
```bash
Error: fatal: not a git repository (or any of the parent directories): .git
```
occurred while executing code-pushup code in a MCP server. But in general we should not throw an error if someone executes the tool without git.

fix: handle repos without git gracefully

---

README.md
packages/cli/package.json

docs(cli): document minimal NodeJS support

---

e2e/nx-plugin-e2e/vite.config.e2e.ts
e2e/plugin-lighthouse-e2e/vite.config.e2e.ts
package-lock.json
package.json
packages/models/docs/models-reference.md
packages/models/src/index.ts
packages/models/src/lib/audit-output.ts
packages/models/src/lib/implementation/schemas.ts
packages/models/src/lib/source.ts
packages/models/src/lib/tree.ts
packages/models/src/lib/tree.unit.test.ts

feat(models): define tree data structure for audit details

---

package-lock.json
package.json
packages/core/package.json
packages/core/src/lib/implementation/report-to-gql.ts
packages/core/src/lib/implementation/report-to-gql.unit.test.ts
packages/models/src/lib/tree.unit.test.ts

feat(core): include trees when uploading audits to portal

---

packages/utils/src/lib/reports/constants.ts
packages/utils/src/lib/reports/formatting.ts
packages/utils/src/lib/reports/generate-md-report.ts
packages/utils/src/lib/reports/generate-md-report.unit.test.ts
packages/utils/src/lib/text-formats/ascii/__snapshots__/basic-tree.txt
packages/utils/src/lib/text-formats/ascii/__snapshots__/basic-tree.with-nesting.txt
packages/utils/src/lib/text-formats/ascii/__snapshots__/basic-tree.with-values.txt
packages/utils/src/lib/text-formats/ascii/__snapshots__/coverage-tree.txt
packages/utils/src/lib/text-formats/ascii/__snapshots__/coverage-tree.with-missing-lines.txt
packages/utils/src/lib/text-formats/ascii/__snapshots__/coverage-tree.with-missing-named.txt
packages/utils/src/lib/text-formats/ascii/tree.ts
packages/utils/src/lib/text-formats/ascii/tree.unit.test.ts

feat(utils): generate ascii tree in full markdown report's audit details

---

packages/plugin-lighthouse/src/lib/runner/details/__snapshots__/critical-request-chain.type.unit.test.ts.snap
packages/plugin-lighthouse/src/lib/runner/details/__snapshots__/treemap-data.type.unit.test.ts.snap
packages/plugin-lighthouse/src/lib/runner/details/critical-request-chain.type.ts
packages/plugin-lighthouse/src/lib/runner/details/critical-request-chain.type.unit.test.ts
packages/plugin-lighthouse/src/lib/runner/details/details.ts
packages/plugin-lighthouse/src/lib/runner/details/details.unit.test.ts
packages/plugin-lighthouse/src/lib/runner/details/treemap-data.type.ts
packages/plugin-lighthouse/src/lib/runner/details/treemap-data.type.unit.test.ts

feat(plugin-lighthouse): include details from criticalrequestchain and treemap-data

---

packages/ci/src/lib/cli/commands/print-config.ts
packages/ci/src/lib/run.integration.test.ts

Should fix error from codebase where Nx target is run in project directory :crossed_fingers:

fix(ci): use absolute path in print-config --output file

---

packages/ci/src/lib/cli/commands/print-config.ts
packages/ci/src/lib/cli/context.ts
packages/ci/src/lib/cli/context.unit.test.ts
packages/ci/src/lib/monorepo/handlers/nx.ts
packages/ci/src/lib/monorepo/handlers/nx.unit.test.ts
packages/ci/src/lib/monorepo/handlers/turbo.ts
packages/ci/src/lib/monorepo/handlers/turbo.unit.test.ts
packages/ci/src/lib/monorepo/list-projects.unit.test.ts
packages/ci/src/lib/run.integration.test.ts

Turns out some Nx monorepos need to cache commands like `print-config` and `compare` as well. Previously, `--skip-nx-cache` was added in #942 due to difficulty in configuring Nx cache correctly for these commands. Adjusted the output files to match expected `{workspaceRoot}/.code-pushup/{projectName}` cache configuration.

feat(ci): make print-config and compare commands nx cache friendly

---

.github/ISSUE_TEMPLATE/plugin-request.yaml
.github/workflows/ci.yml
CONTRIBUTING.md
nx.json
package-lock.json
package.json

Follow-up to:
- #1018
- push-based/nx-verdaccio#79
Now all test targets follow the `<type>-test` naming pattern:
- `unit-test` - execute unit tests
- `int-test` - execute integration tests
- `e2e-test` - execute end-to-end tests

test: rename nxv-e2e target to e2e-test

---

packages/plugin-js-packages/src/lib/package-managers/package-managers.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-classic/audit-result.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-classic/audit-result.unit.test.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-classic/constants.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-classic/outdated-result.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-classic/outdated-result.unit.test.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-classic/types.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-classic/yarn-classic.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-modern/audit-result.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-modern/audit-result.unit.test.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-modern/outdated-result.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-modern/outdated-result.unit.test.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-modern/types.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-modern/yarn-modern.ts
packages/plugin-js-packages/src/lib/runner/audit/types.ts
packages/plugin-js-packages/src/lib/runner/audit/utils.ts
packages/plugin-js-packages/src/lib/runner/audit/utils.unit.test.ts

Fixes bug reported by customer trying to integrate packages audit in Yarn v4.
Found out that in Yarn version 4, the output format of `yarn npm audit --json` changed completely compared to versions 2 and 3. Adjusted the stdout parsing logic to support both formats. Tested in `rx-angular` workspace.

fix(plugin-js-packages): parse yarn 4 audit output correctly

---

packages/plugin-js-packages/src/lib/package-managers/constants.ts
packages/plugin-js-packages/src/lib/package-managers/npm/npm.ts
packages/plugin-js-packages/src/lib/package-managers/pnpm/pnpm.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-classic/yarn-classic.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-modern/outdated-result.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-modern/outdated-result.unit.test.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-modern/types.ts
packages/plugin-js-packages/src/lib/package-managers/yarn-modern/yarn-modern.ts

Yarn Berry's [`yarn npm audit`](https://yarnpkg.com/cli/npm/audit) command by default only reports vulnerabilities in direct dependencies, not transitive dependencies. Adding `--recursive` flag brings it in line with audit commands from other package managers.
Also, found out that it's possible to get outdated package URLs in [`yarn-plugin-outdated`](https://github.com/mskelton/yarn-plugin-outdated?tab=readme-ov-file#display-homepage-urls---url) by adding `--url` flag. So reported issues for Yarn Berry should now include Markdown links, not just the package name.

fix(plugin-js-packages): for modern yarn, include transitive deps in audit and urls in outdated

---

README.md

Uses portal's new badges API to render live category scores for this repo. For security, the API key is restricted to `read:reports` scope and has access only to the Code PushUp CLI project in the portal.

docs: add category badges from portal

---

code-pushup.preset.ts
e2e/plugin-lighthouse-e2e/tests/__snapshots__/collect.e2e.test.ts.snap
packages/cli/src/lib/implementation/filter.middleware.ts
packages/cli/src/lib/implementation/filter.middleware.unit.test.ts
packages/models/src/index.ts
packages/models/src/lib/plugin-config.ts
packages/plugin-lighthouse/README.md
packages/plugin-lighthouse/src/index.ts
packages/plugin-lighthouse/src/lib/constants.ts
packages/plugin-lighthouse/src/lib/lighthouse-plugin.ts
packages/plugin-lighthouse/src/lib/lighthouse-plugin.unit.test.ts
packages/plugin-lighthouse/src/lib/merge-categories.ts
packages/plugin-lighthouse/src/lib/merge-categories.unit.test.ts
packages/plugin-lighthouse/src/lib/processing.ts
packages/plugin-lighthouse/src/lib/processing.unit.test.ts
packages/plugin-lighthouse/src/lib/runner/runner.ts
packages/plugin-lighthouse/src/lib/runner/runner.unit.test.ts
packages/plugin-lighthouse/src/lib/runner/utils.ts
packages/plugin-lighthouse/src/lib/runner/utils.unit.test.ts
packages/plugin-lighthouse/src/lib/types.ts
packages/plugin-lighthouse/src/lib/utils.ts
packages/plugin-lighthouse/vitest.unit.config.ts

Closes #1008 
This PR  adds support for running Lighthouse on multiple URLs to provide holistic performance and accessibility analysis across different pages.
- Multiple URL input: Accept `string | string[] | Record<string, number>` for the `urls` parameter
- Sequential execution: Run Lighthouse on each URL sequentially
- URL-specific audits: Generate distinct audit slugs with numbered suffixes (e.g., `first-contentful-paint-1`, `first-contentful-paint-2`)
- URL-specific groups: Create separate groups for each URL with descriptive titles including the URL and slugs including numbered suffixes
- Category aggregation: Provide `mergeLighthouseCategories` helper to combine results across URLs
- Backward compatibility: Single URL functionality remains unchanged
```ts
// Single URL (unchanged) …
```

feat(plugin-lighthouse): implement multiple URL support

---

packages/ci/src/lib/run-utils.ts
packages/ci/src/lib/run.int.test.ts

Part of an effort to avoid extra CLI arguments which restrict cache reuse in Nx monorepos (related to #1040).
The `--verbose` flag was being set by default, which was probably an unintended consequence of #952. Tweaked the logic so that only explicitly setting `debug: true` or `silent: false` enables verbosity.

fix(ci): do not set --verbose by default

---

e2e/ci-e2e/global-setup.ts
e2e/ci-e2e/tsconfig.test.json
e2e/ci-e2e/vitest.e2e.config.ts
packages/ci/src/lib/cli/commands/collect.ts
packages/ci/src/lib/run-monorepo.ts
packages/ci/src/lib/run-utils.ts
packages/ci/src/lib/run.int.test.ts

Final piece from larger effort to avoid CLI arguments which reduce chances of Nx cache hits in default setup. See also:
- #1040
- #1041
The CLI arguments `--persist.format=json --persist.format=md` were being set in case user-defined config omitted report formats which `@code-pushup/ci` relies on. After this refactor, the configured formats are first checked in `print-config` output, and then only set if some format is missing - in monorepo mode with bulk collect, every project must have default formats configured in order to skip the CLI arguments.
TLDR: `--persist.format` args are now skipped unless user has some unusual config.

feat(ci): skip persist.format args if defaults already configured

---

eslint.config.js
package-lock.json
package.json
packages/ci/mocks/fixtures/outputs/config.portal.json
packages/ci/mocks/fixtures/outputs/diff-project.json
packages/ci/mocks/fixtures/outputs/report-after.json
packages/ci/mocks/fixtures/outputs/report-before.json
packages/ci/mocks/fixtures/outputs/report-before.portal.json
packages/ci/package.json
packages/ci/src/lib/cli/index.ts
packages/ci/src/lib/cli/persist.ts
packages/ci/src/lib/cli/persist.unit.test.ts
packages/ci/src/lib/portal/__snapshots__/transform.unit.test.ts.snap
packages/ci/src/lib/portal/download.ts
packages/ci/src/lib/portal/index.ts
packages/ci/src/lib/portal/transform.ts
packages/ci/src/lib/portal/transform.unit.test.ts
packages/ci/src/lib/run-monorepo.ts
packages/ci/src/lib/run-utils.ts
packages/ci/src/lib/run.int.test.ts
packages/core/package.json
packages/utils/src/index.ts
packages/utils/src/lib/case-conversion.type.test.ts
packages/utils/src/lib/case-conversions.ts
packages/utils/src/lib/case-conversions.unit.test.ts
packages/utils/src/lib/env.unit.test.ts
packages/utils/vitest.unit.config.ts
testing/test-setup/src/lib/portal-client.mock.ts

For CI environments were artifact caching is difficult to configure (e.g. CircleCI), caching the previous report from the portal is a good alternative. 
This PR implements a zero-config version where we check for `upload` configuration in `print-config` output and, if it's present, we prioritize fetching the previous report from portal (reusing same server parameters) rather than CI artifacts.
In a follow-up PR, I'll implement an optimized version where a monorepo user can provide their `persist` and `upload` config patterns upfront in order to not waste time on running `print-config` commands. This is related to:
- #1043

feat(ci): download previous report from portal if available

---

packages/ci/README.md
packages/ci/src/lib/cli/context.unit.test.ts
packages/ci/src/lib/constants.ts
packages/ci/src/lib/models.ts
packages/ci/src/lib/monorepo/handlers/nx.ts
packages/ci/src/lib/run-monorepo.ts
packages/ci/src/lib/run-utils.ts
packages/ci/src/lib/run.int.test.ts
packages/utils/src/index.ts
packages/utils/src/lib/interpolate.ts
packages/utils/src/lib/interpolate.unit.test.ts
packages/utils/src/lib/types.ts

1st half of #1043 
Adds `configPatterns` option, which allows skipping per-project `print-config` executions.

feat(ci): add configPatterns as optional performance optimization

---

package-lock.json
package.json
packages/ci/README.md
packages/ci/package.json
packages/ci/src/lib/constants.ts
packages/ci/src/lib/models.ts
packages/ci/src/lib/portal/download.ts
packages/ci/src/lib/portal/index.ts
packages/ci/src/lib/run-utils.ts
packages/ci/src/lib/run.int.test.ts
packages/cli/src/lib/autorun/autorun-command.unit.test.ts
packages/cli/src/lib/upload/upload-command.unit.test.ts
packages/core/package.json
packages/core/src/lib/upload.ts
packages/core/src/lib/upload.unit.test.ts
testing/test-setup/src/lib/portal-client.mock.ts

Reuses `latestReport` resolver from GraphQL API for a more wide-ranging search for previous report in Portal. Useful for Nx users who always run with `--affected`, increases chances of cache hit for projects which don't change much. The range can be configured, maximum number of commits is 100, default is 10.

feat(ci): add searchCommits option to extend portal cache range

---

examples/plugins/src/file-size/src/file-size.plugin.int.test.ts
examples/plugins/src/package-json/src/package-json.plugin.int.test.ts
packages/core/src/index.ts
packages/core/src/lib/implementation/collect.ts
packages/core/src/lib/implementation/execute-plugin.ts
packages/core/src/lib/implementation/execute-plugin.unit.test.ts
packages/core/src/lib/implementation/runner.int.test.ts
packages/core/src/lib/implementation/runner.ts
packages/core/src/lib/implementation/runner.unit.test.ts
packages/models/src/index.ts
packages/models/src/lib/cache-config.ts

- add `utils` for runner result caching
- add cache options to `executePlugin` and `executePlugins`
- add `CacheConfig` to `models` package and use it in `core` package
Related:
#1048

feat: add audit output caching for execute plugin

---

e2e/ci-e2e/tests/nx-monorepo.e2e.test.ts

We have a flaky test that keeps timing out on Windows, e.g. [here](https://cloud.nx.app/runs/IFBBWixS8i/task/ci-e2e%3Ae2e), [here](https://cloud.nx.app/runs/GVYxUxqCzn), [here](https://cloud.nx.app/runs/KKqqhuAlrc). Hopefully, doubling the timeout should help :crossed_fingers:

test(ci-e2e): fix nx pr test from timing out on windows

---

nx.json

We run CI jobs on different operating systems to ensure platform compatibility. Now that Nx Cloud is in play, though, we need to make sure cache isn't reused between them - the same source code may pass on Linux and fail on Windows, for example.
I've set the `os.platform()` value (along with `node -v`) as a shared global, so that Nx uses this info in its cache keys. I've tested the command on both Linux and Windows to make sure it works everywhere (not easy to figure out, different shells, quote handling etc. :sweat_smile:), came up with `node -e "console.log(require('os').platform())"`.

ci: invalidate nx cloud cache for different operating system

---

.github/workflows/ci.yml
.gitignore
code-pushup.preset.ts
nx.json
packages/ci/project.json
packages/cli/project.json
packages/core/project.json
packages/create-cli/project.json
packages/models/project.json
packages/nx-plugin/project.json
packages/plugin-coverage/project.json
packages/plugin-eslint/project.json
packages/plugin-js-packages/project.json
packages/plugin-jsdocs/project.json
packages/plugin-lighthouse/project.json
packages/plugin-typescript/project.json
packages/utils/project.json

- adjust existing `lint` target in `nx.json#defaultTargtets`
- add `lint-report` target `nx.json#defaultTargtets`
- add empty `lint-report` target to all projects
Related:
- #1068

chore: add lint report target

---

packages/ci/src/lib/run-monorepo.ts
packages/ci/src/lib/run-utils.ts
packages/models/docs/models-reference.md

2 different monorepos have encountered the same bug, recently. It happens towards the end of the run, after bulk compare has completed succesfully.
```
NX   Successfully ran target code-pushup for 8 projects
file:///home/runner/work/_actions/code-pushup/github-action/v0/node_modules/simple-git/dist/esm/index.js:4462
return { error: new GitError(void 0, error.toString("utf-8")) };
^
Error: fatal: Unable to create '/home/runner/work/radar-kit-fu/radar-kit-fu/.git/shallow.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
at Object.action …
```

fix(ci): prevent parallel git diff when detecting new issues in monorepo

---

e2e/plugin-eslint-e2e/mocks/fixtures/artifacts-config/code-pushup.config.ts
e2e/plugin-eslint-e2e/mocks/fixtures/artifacts-config/eslint.config.cjs
e2e/plugin-eslint-e2e/mocks/fixtures/artifacts-config/src/index.js
e2e/plugin-eslint-e2e/tests/__snapshots__/collect.e2e.test.ts.snap
e2e/plugin-eslint-e2e/tests/collect.e2e.test.ts
nx.json
packages/plugin-eslint/README.md

- docs for `plugin-eslint`
- e2e tests `plugin-eslint-e2e`

refactor(plugin-eslint): artifacts e2e tests and docs

---

.github/workflows/release.yml
CHANGELOG.md
packages/ci/package.json
packages/cli/package.json
packages/core/package.json
packages/create-cli/package.json
packages/models/package.json
packages/nx-plugin/package.json
packages/plugin-coverage/package.json
packages/plugin-eslint/package.json
packages/plugin-js-packages/package.json
packages/plugin-jsdocs/package.json
packages/plugin-lighthouse/package.json
packages/plugin-typescript/package.json
packages/utils/package.json

- Closes #1114 
- Closes #893
- Enabled previously disabled [`release.yml`](https://github.com/code-pushup/cli/actions/workflows/release.yml) workflow.
- Removed `NPM_TOKEN` secret. Instead, the `release.yml` workflow is configured as a trusted publisher and uses OIDC authentication. This is configured in the [_Settings_ tab](https://www.npmjs.com/package/@code-pushup/cli/access) for each package:
- Provenance attestations are now automatically generated for all packages, see [example](https://www.npmjs.com/package/@code-pushup/cli/v/0.79.2-alpha.1#provenance-details-header):
- Removed unnecessary GitHub App authentication. The `id-token: write` (for OIDC) and `contents: write` (for GitHub Release) permissions are sufficient.
- Removed unnecessary `dry-run` logic and `workflow-dispatch`. …

ci: fix automated releases

---

packages/utils/src/index.ts
packages/utils/src/lib/types.ts

Adding a useful type helper, discussed in other PRs.

feat(utils): export loose autocomplete type helper

---

.github/workflows/release.yml

Possible fix for #1114. Follow-up to #1117.
Turns out the default `github-actions[bot]` can't push to `main` (see [CI error](https://github.com/code-pushup/cli/actions/runs/17969395646/job/51108271743#step:6:318)):
>  NX   Pushing to git remote "origin"
> 
> 
>  NX   Unexpected git push error: remote: error: GH006: Protected branch update failed for refs/heads/main.        
> 
> remote: 
> remote: - Changes must be made through a pull request.        
> To https://github.com/code-pushup/cli
>  ! [remote rejected]   main -> main (protected branch hook declined)
>  ! [remote rejected]   v0.80.0 -> v0.80.0 (atomic transaction failed)
> error: failed to push some refs to 'https://github.com/code-pushup/cli'
This is probably why the `code-pushup-bot` was used before, because unlike the …

ci: fix protected branch error in release workflow

---

packages/models/project.json

This PR fixes a slightly annoying local development problem.
The `models:generate-docs` target is being run automatically for each `models:build`, which is fairly frequent because other tasks often depend on `build` (e.g. `e2e-test`, or recently `lint`). This itself is fine, but because the Markdown generated by `zod2md` is 100% the same as how Prettier would format it, you often end up having a local change to `models-reference.md`. It disappears once you commit, because our `pre-commit` hook formats files with `prettier`, which effectively reverts the file changes. So it's not a big deal, but it still happens often enough to be a nuisance.
```diff
diff --git a/packages/models/docs/models-reference.md b/packages/models/docs/models-reference.md
index 0782c525..9013123d 100644
--- …
```

build(models): run prettier immediately after zod2md docs generation

---

packages/plugin-lighthouse/src/lib/runner/runner.ts
packages/plugin-lighthouse/src/lib/runner/utils.ts
packages/plugin-lighthouse/src/lib/runner/utils.unit.test.ts

Fixes #1122
The permissions error seems to be a cleanup bug in `lighthouse`/`chrome-launcher` (see GoogleChrome/chrome-launcher#355). Overriding the default system temporary directory path on Windows to a local path [fixes the tests](https://github.com/code-pushup/cli/actions/runs/18037951230/job/51329257914?pr=1124#step:6:56).
From Node.js [`os.tmpdir()` docs](https://nodejs.org/api/os.html#ostmpdir):
> On Windows, the result can be overridden by `TEMP` and `TMP` environment variables, and `TEMP` takes precedence over `TMP`. If neither is set, it defaults to `%SystemRoot%\temp` or `%windir%\temp`.
> 
> On non-Windows platforms, `TMPDIR`, `TMP` and `TEMP` environment variables will be checked to override the result of this method, in the described order. If none of them is set, it …

fix(plugin-lighthouse): prevent cleanup permissions error on windows

---

e2e/nx-plugin-e2e/tests/__snapshots__/plugin-create-nodes.e2e.test.ts.snap
e2e/nx-plugin-e2e/tests/generator-configuration.e2e.test.ts
e2e/nx-plugin-e2e/tests/plugin-create-nodes.e2e.test.ts
packages/nx-plugin/src/generators/configuration/generator.int.test.ts
packages/nx-plugin/src/generators/configuration/generator.ts
packages/nx-plugin/src/generators/configuration/schema.json
packages/nx-plugin/src/plugin/plugin.unit.test.ts
packages/nx-plugin/src/plugin/target/configuration-target.ts
packages/nx-plugin/src/plugin/target/configuration.target.unit.test.ts
packages/nx-plugin/src/plugin/target/targets.ts
packages/nx-plugin/src/plugin/target/targets.unit.test.ts

This PR:
- removes the generator to add a target to a project. from V19 on this is done over plugins

refactor: remove target generator in favour of task inference
